### ISSUE TITLE
Plot window re-opens immediately after closing

### ISSUE THREAD

**Issue by hakonanes** [pyvista/pyvista#4057] opened 2023-02-23 09:08 UTC
### Describe the bug, what's wrong, and what you expected.

Running a minimal example with PyVista, the plot window re-opens immediately after closing. The re-opened window is not responsive.

Re-installing older versions of vtk shows that I get this behaviour with v9.2.4 but *not with v.9.2.2*. The behaviour might be related to https://gitlab.kitware.com/vtk/vtk/-/issues/18652. I should perhaps have reported this issue there instead using vtk directly, but I have never used vtk before... Feel free to close this issue if there is nothing that can be done in PyVista to mitigate this behaviour.

### Steps to reproduce the bug.

```python
import pyvista as pv
pv.Cone().plot()
```

### System Information

```shell
--------------------------------------------------------------------------------
  Date: Thu Feb 23 10:07:56 2023 CET

                OS : Linux
            CPU(s) : 4
           Machine : x86_64
      Architecture : 64bit
       Environment : Python
        GPU Vendor : Intel
      GPU Renderer : Mesa Intel(R) HD Graphics 620 (KBL GT2)
       GPU Version : 4.6 (Core Profile) Mesa 22.2.5

  Python 3.10.9 | packaged by conda-forge | (main, Feb  2 2023, 20:20:04) [GCC
  11.3.0]

           pyvista : 0.38.3
               vtk : 9.2.6
             numpy : 1.24.2
           imageio : 2.25.1
            scooby : 0.7.1
             pooch : v1.6.0
        matplotlib : 3.7.0
--------------------------------------------------------------------------------
```

### Screenshots

![Peek 23-02-2023 09-51](https://user-images.githubusercontent.com/12139781/220863911-c431a212-ddbf-42d8-aa9f-331fee947e74.gif)

**Comment by banesullivan** [comment] 2023-02-23 15:27
Looks like a duplicate of https://github.com/pyvista/pyvista/issues/1096#issuecomment-1374000281, which recently started happening on Linux too.

@akaszynski, did you end up looking into this on linux?

**Comment by hakonanes** [comment] 2023-03-09 08:28
This solved my issue, thanks!

**Closed** 2023-03-09 16:43 UTC
Labels: bug
