### ISSUE TITLE
Measurement widget snaps to points on mesh

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvista#588] opened 2020-02-05 19:34 UTC
I would really love to have a measurement tool/widget that would use PyVista'a picking tools to snap the tool to points on meshes in the scene and let a user measure the distances between points or along the edge of a mesh.

We'd leverage [`vtkDistanceWidget`](https://vtk.org/doc/nightly/html/classvtkDistanceWidget.html) but add on some sort of point snapping feature

I am putting this here as a feature request in case someone else is up for trying this out or has tips on how this should work/look.

-----

For example, I'm often in an expansive scene and need to know the scale of what I am looking at and axes grids simply don't cut it. When I zoom in here, it'd be awesome if I could pick the top and bottom of the profiles there to show the length/depth and leave a little ruler with text in the scene

![2020-02-05 12 30 27](https://user-images.githubusercontent.com/22067021/73875949-553f1f00-4813-11ea-84f1-0a63040e698f.gif)

**Comment by banesullivan** [comment] 2020-02-08 23:18
Following up. Its easy to get a ruler widget in the scene, but I haven't yet figured out how to do point snapping to the meshes:

```py
import vtk
import pyvista as pv

p = pv.Plotter(notebook=0)
p.add_mesh(pv.Sphere(), opacity=0.75)

widget = vtk.vtkDistanceWidget()
widget.SetInteractor(p.iren)

handle = vtk.vtkPointHandleRepresentation3D()
representation = vtk.vtkDistanceRepresentation2D()
representation.SetHandleRepresentation(handle)
widget.SetRepresentation(representation)

widget.SetPickingManaged(False)
widget.On()

p.show(auto_close=False)
widget.Off()
del widget
p.close()
```

![2020-02-08 16 18 02](https://user-images.githubusercontent.com/22067021/74093402-9d1daa80-4a8e-11ea-8fbb-3d26315caabe.gif)

**Comment by banesullivan** [comment] 2020-02-08 23:59
And... I figured it out:

```py
import vtk
import pyvista as pv
from pyvista import examples

mesh = examples.load_random_hills()

p = pv.Plotter(notebook=0)
p.add_mesh(mesh, show_edges=True)

widget = vtk.vtkDistanceWidget()
widget.SetInteractor(p.iren)

handle = vtk.vtkPointHandleRepresentation3D()
representation = vtk.vtkDistanceRepresentation2D()
representation.SetHandleRepresentation(handle)
widget.SetRepresentation(representation)
point_picker = vtk.vtkPointPicker()
p.iren.SetPicker(point_picker)

def place_point(widget, event):
    p1 = [0, 0, 0]
    p2 = [0, 0, 0]
    pos1 = None
    pos2 = None
    representation.GetPoint1DisplayPosition(p1)
    representation.GetPoint2DisplayPosition(p2)
    if point_picker.Pick(p1, p.renderer):
        pos1 = point_picker.GetPickPosition()
        selPt = point_picker.GetSelectionPoint()
        pos12 = selPt[0:2]
        representation.GetPoint1Representation().SetWorldPosition(pos1)
        representation.GetAxis().GetPoint1Coordinate().SetValue(pos1)
    if point_picker.Pick(p2, p.renderer):
        pos2 = point_picker.GetPickPosition()
        selPt = point_picker.GetSelectionPoint()
        pos22 = selPt[0:2]
        representation.GetPoint2Representation().SetWorldPosition(pos2)
        representation.GetAxis().GetPoint2Coordinate().SetValue(pos2)
    representation.BuildRepresentation()
    return

    
widget.AddObserver(vtk.vtkCommand.EndInteractionEvent., place_point)

widget.On()

p.show(auto_close=False)
widget.Off()
del widget
p.close()
```


![2020-02-08 16 57 58](https://user-images.githubusercontent.com/22067021/74093797-4e730f00-4a94-11ea-8479-27d2536d4a6e.gif)

**Comment by banesullivan** [comment] 2020-02-09 00:01
When we add this, we should refactor the point picking stuff to only allow one `vtkPointPicker` on the Plotter so that we can have several ruler widgets and still enable the point picking method

**Comment by banesullivan** [comment] 2020-02-09 06:30
There's also a 3D representation which is a little cleaner but more difficult to control:


```py
import vtk
import pyvista as pv
from pyvista import examples

mesh = examples.download_foot_bones()

pv.set_plot_theme("default")

p = pv.Plotter(notebook=0)
p.add_mesh(mesh, show_edges=True, color="lightblue")

widget = vtk.vtkDistanceWidget()
widget.SetInteractor(p.iren)

handle = vtk.vtkPointHandleRepresentation3D()
representation = vtk.vtkDistanceRepresentation3D()
representation.SetHandleRepresentation(handle)
widget.SetRepresentation(representation)
point_picker = vtk.vtkPointPicker()
p.iren.SetPicker(point_picker)

def place_point(widget, event):
    p1 = [0, 0, 0]
    p2 = [0, 0, 0]
    representation.GetPoint1DisplayPosition(p1)
    representation.GetPoint2DisplayPosition(p2)
    if point_picker.Pick(p1, p.renderer):
        pos1 = point_picker.GetPickPosition()
        representation.GetPoint1Representation().SetWorldPosition(pos1)
    if point_picker.Pick(p2, p.renderer):
        pos2 = point_picker.GetPickPosition()
        representation.GetPoint2Representation().SetWorldPosition(pos2)
    representation.BuildRepresentation()
    return

    
widget.AddObserver(vtk.vtkCommand.EndInteractionEvent, place_point)

widget.On()

p.show(auto_close=False)
widget.Off()
del widget
p.close()
```

**Comment by russelldj** [comment] 2020-08-26 16:43
I think this may be more intuitive if the measurement tool can snap to the surface nearest the camera when interacting with meshes. I'm having issues with complex/noisy meshes where it snaps to background objects. Since this is in line with the viewing ray, this isn't initially obvious. Thoughts? I can take a look at this general issue as time allows.

**Comment by banesullivan** [comment] 2020-09-28 04:03
> where it snaps to background objects.

By this, do you mean parts of the same mesh that should be behind the currently visible part of the surface?

We should be able to adjust the picker to leverage hardware picking and do a better job of this... It'd likely use `vtkOpenGLHardwareSelector` with `.SetFieldAssociation(vtk.vtkDataObject.FIELD_ASSOCIATION_POINTS)`. there is some nuanced code in the `picking` module that does this for cell selections:

https://github.com/pyvista/pyvista/blob/b4321ff35dbe70824cf80e9d699e173864b361e0/pyvista/plotting/picking.py#L137-L164

Feel free to ping me with an example mesh for this and I can at least take a look

**Comment by Ahmadalaili** [comment] 2021-08-30 21:23
Hello, I am trying to use your code but getting this error in python 3.8 using PyCharm
Traceback (most recent call last):
  File "C:/Users/User/PycharmProjects/Open3D/cpp/measurement tool.py", line 28, in <module>
    widget.SetInteractor(p.iren)
TypeError: SetInteractor argument %Id: %V
Any suggestions? 
Thank you in advance.

**Comment by Michael-P-Crisp** [comment] 2023-01-25 00:37
Hi,

I'm posting this issue here since it's literally the only page I found on google talking about doing measurements in PyVista.

I've copied the code from this discussion but I'm getting an error on the SetInteractor line in the below block.
"TypeError: SetInteractor argument 1: method requires a VTK object"

```
import vtk
import pyvista as pv

p = pv.Plotter()
widget = vtk.vtkDistanceWidget()
widget.SetInteractor(p.iren)
```

Could someone please help with this? I'm using python 3.10.9, PyVista 0.37.0 and vtk 9.2.5.

**Comment by banesullivan** [comment] 2023-01-25 01:54
I'm actually actively working on this in #3718 - take a look at the code there. Hopefully I can wrap it up for the 0.38 release which is coming in the next few weeks

**Comment by banesullivan** [comment] 2023-01-25 02:02
FWIW, there was a change of `iren` in PyVista. Here is a working example:

```py
import vtk
import pyvista as pv
from pyvista import examples

mesh = examples.download_foot_bones()

pv.set_plot_theme("default")

p = pv.Plotter(notebook=0)
p.add_mesh(mesh, show_edges=True, color="lightblue")

widget = vtk.vtkDistanceWidget()
widget.SetInteractor(p.iren.interactor)

handle = vtk.vtkPointHandleRepresentation3D()
representation = vtk.vtkDistanceRepresentation3D()
representation.SetHandleRepresentation(handle)
widget.SetRepresentation(representation)
point_picker = vtk.vtkPointPicker()
p.iren.interactor.SetPicker(point_picker)

def place_point(widget, event):
    p1 = [0, 0, 0]
    p2 = [0, 0, 0]
    representation.GetPoint1DisplayPosition(p1)
    representation.GetPoint2DisplayPosition(p2)
    if point_picker.Pick(p1, p.renderer):
        pos1 = point_picker.GetPickPosition()
        representation.GetPoint1Representation().SetWorldPosition(pos1)
    if point_picker.Pick(p2, p.renderer):
        pos2 = point_picker.GetPickPosition()
        representation.GetPoint2Representation().SetWorldPosition(pos2)
    representation.BuildRepresentation()
    return

    
widget.AddObserver(vtk.vtkCommand.EndInteractionEvent, place_point)

widget.On()

p.show(auto_close=False)
widget.Off()
del widget
p.close()
```

**Comment by Michael-P-Crisp** [comment] 2023-01-25 02:17
Thanks!

Ideally my measurements would snap to a surface, but in any case this is very nice. I'm looking forward to seeing the official widget in action in 0.38.

I see you can drag the measuring line's end points, although Is there some way to redo the measurement from scratch without closing the window?

**Comment by banesullivan** [comment] 2023-01-25 02:25
> Ideally my measurements would snap to a surface, but in any case this is very nice

They do snap to the surface in the example above:

https://user-images.githubusercontent.com/22067021/214466793-639cfb6f-69eb-4557-8c26-fb424b3baa42.mov




> I see you can drag the measuring line's end points, although Is there some way to redo the measurement from scratch without closing the window?

I'll see if this is easy to implement while working on #3718

**Comment by Michael-P-Crisp** [comment] 2023-01-25 03:21
Cheers!

The issue is that if you have some meshes with very simple geometry, and very large faces, it will snap to the corner of that geometry rather than the interior. There may be cases, particularly with textured meshes, where it is desirable to measure distances between points. 

I.e. when I mentioned surfaces earlier, I meant the faces rather than the vertices.

**Closed** 2023-06-29 04:14 UTC
Labels: feature-request
