### ISSUE TITLE
Detect holes boundary in pointcloud data?

### ISSUE THREAD

**Issue by AI-ML-Enthusiast** [pyvista/pyvista#1785] opened 2021-11-07 03:39 UTC
I can detection hole using pyvista from mesh.
https://pymeshfix.pyvista.org/examples/repair_planar.html

I want to detect hole boundary in pointcloud using pyvista? is there any function in pyvista or way to do that?

Thanks

**Comment by akaszynski** [comment] 2021-11-07 20:10
I think your best bet would be to attempt a surface reconstruction using the [reconstruct_surface](https://docs.pyvista.org/examples/01-filter/surface_reconstruction.html) filter and then use the [extract_feature_edges](https://docs.pyvista.org/api/core/_autosummary/pyvista.DataSet.extract_feature_edges.html?highlight=extract_feature_edges#pyvista.DataSet.extract_feature_edges) filter to grab the largest boundaries of the surface.

**Comment by AI-ML-Enthusiast** [comment] 2021-11-07 23:32
> I think your best bet would be to attempt a surface reconstruction using the [reconstruct_surface](https://docs.pyvista.org/examples/01-filter/surface_reconstruction.html) filter and then use the [extract_feature_edges](https://docs.pyvista.org/api/core/_autosummary/pyvista.DataSet.extract_feature_edges.html?highlight=extract_feature_edges#pyvista.DataSet.extract_feature_edges) filter to grab the largest boundaries of the surface.

Thank you very much for your comment.
If the pointcloud is converted into the surface (reconstruct_surface), the vertices will be the same as the pointcloud or not? 
if yes, it is OK? but if they are not same, how can I back to pointcloud and localize the hole in the pointcloud?

**Comment by banesullivan** [comment] 2021-11-26 23:47
Duplicate of https://github.com/pyvista/pyvista/discussions/1787. Closing.

**Closed by banesullivan** 2021-11-26 23:47 UTC
Labels: feature-request
