### ISSUE TITLE
UnstructuredGrid.clean modifies cell faces in-place

### ISSUE THREAD

**Issue by dionhaefner** [pyvista/pyvista#6208] opened 2024-06-05 10:53 UTC
### Describe the bug, what's wrong, and what you expected.

I'm observing this behavior:

```python
def inspect_cell(mesh, cellid):
    print(cell.point_ids)

    for face in cell.faces:
        print(face.point_ids)

    cell.cast_to_unstructured_grid().plot()

msh = pv.read("msh.vtu")

# all good
inspect_cell(msh, 6813)

# call UnstructuredGrid.clean, and throw away returned mesh
_ = msh.clean()

# 💀 original mesh is now broken
inspect_cell(msh, 6813)
```

Traceback:

```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[8], [line 8](vscode-notebook-cell:?execution_count=8&line=8)
      [5](vscode-notebook-cell:?execution_count=8&line=5) for face in cell.faces:
      [6](vscode-notebook-cell:?execution_count=8&line=6)     print(face.point_ids)
----> [8](vscode-notebook-cell:?execution_count=8&line=8) cell.cast_to_unstructured_grid().plot()

File ~/.virtualenvs/science/lib/python3.10/site-packages/pyvista/core/cell.py:235, in Cell.cast_to_unstructured_grid(self)
    [233](https://file+.vscode-resource.vscode-cdn.net/Users/dion/codes/supersede/~/.virtualenvs/science/lib/python3.10/site-packages/pyvista/core/cell.py:233)     for face in self.faces:
    [234](https://file+.vscode-resource.vscode-cdn.net/Users/dion/codes/supersede/~/.virtualenvs/science/lib/python3.10/site-packages/pyvista/core/cell.py:234)         cell_ids.append(len(face.point_ids))
--> [235](https://file+.vscode-resource.vscode-cdn.net/Users/dion/codes/supersede/~/.virtualenvs/science/lib/python3.10/site-packages/pyvista/core/cell.py:235)         cell_ids.extend(self.point_ids.index(i) for i in face.point_ids)
    [236](https://file+.vscode-resource.vscode-cdn.net/Users/dion/codes/supersede/~/.virtualenvs/science/lib/python3.10/site-packages/pyvista/core/cell.py:236)     cell_ids.insert(0, len(cell_ids))
    [237](https://file+.vscode-resource.vscode-cdn.net/Users/dion/codes/supersede/~/.virtualenvs/science/lib/python3.10/site-packages/pyvista/core/cell.py:237) else:

File ~/.virtualenvs/science/lib/python3.10/site-packages/pyvista/core/cell.py:235, in <genexpr>(.0)
    [233](https://file+.vscode-resource.vscode-cdn.net/Users/dion/codes/supersede/~/.virtualenvs/science/lib/python3.10/site-packages/pyvista/core/cell.py:233)     for face in self.faces:
    [234](https://file+.vscode-resource.vscode-cdn.net/Users/dion/codes/supersede/~/.virtualenvs/science/lib/python3.10/site-packages/pyvista/core/cell.py:234)         cell_ids.append(len(face.point_ids))
--> [235](https://file+.vscode-resource.vscode-cdn.net/Users/dion/codes/supersede/~/.virtualenvs/science/lib/python3.10/site-packages/pyvista/core/cell.py:235)         cell_ids.extend(self.point_ids.index(i) for i in face.point_ids)
    [236](https://file+.vscode-resource.vscode-cdn.net/Users/dion/codes/supersede/~/.virtualenvs/science/lib/python3.10/site-packages/pyvista/core/cell.py:236)     cell_ids.insert(0, len(cell_ids))
    [237](https://file+.vscode-resource.vscode-cdn.net/Users/dion/codes/supersede/~/.virtualenvs/science/lib/python3.10/site-packages/pyvista/core/cell.py:237) else:

ValueError: 11434 is not in list
```

It seems like `msh.clean()` is modifying cell faces in-place. After applying `clean`, I get this:

```python
cell.point_ids=[8754, 9333, 9349, 9350, 9351, 9398, 9411, 9413, 10022, 11772, 11773, 11940, 12503, 16295]
cell.face[0].point_ids=[8754, 11434, 12088, 11435]
```

Note that the point `11434` used in face 0 isn't actually part of the cell.

Also, the mesh isn't plotted correctly anymore.

**Before clean**
<img width="723" alt="Screenshot 2024-06-05 at 12 49 41" src="https://github.com/pyvista/pyvista/assets/11994217/1b4be3c7-bb1e-48a9-acda-9f89033e21b8">

**After clean**
<img width="723" alt="Screenshot 2024-06-05 at 12 49 17" src="https://github.com/pyvista/pyvista/assets/11994217/7366120a-a8ae-41d2-8fbb-2ce3cf5ffa9a">

---

So there are actually multiple issues here:
1. `UnstructuredGrid.clean` operates partly in-place when it shouldn't.
2. `UnstructuredGrid.clean` modifies cell faces incorrectly (adds points that are not part of `cell.point_ids`), ~~**also in the returned mesh**~~ incorrect, returned mesh is fine.
3. The mesh (or plotting) seems broken post-clean, perhaps as a consequence of (2).

### Steps to reproduce the bug.

Notebook and mesh file to reproduce:

[pv-bug.zip](https://github.com/user-attachments/files/15585626/pv-bug.zip)

### System Information

```shell
--------------------------------------------------------------------------------
  Date: Wed Jun 05 12:46:38 2024 CEST

                  OS : Darwin
              CPU(s) : 10
             Machine : arm64
        Architecture : 64bit
                 RAM : 16.0 GiB
         Environment : Python
         File system : apfs
          GPU Vendor : Apple
        GPU Renderer : Apple M1 Pro
         GPU Version : 4.1 Metal - 88.1
    MathText Support : True

  Python 3.10.13 (main, Aug 24 2023, 12:59:26) [Clang 15.0.0
  (clang-1500.0.40.1)]

             pyvista : 0.43.1
                 vtk : 9.2.6
               numpy : 1.26.1
          matplotlib : 3.8.0
              scooby : 0.7.1
               pooch : v1.7.0
              pillow : 9.1.0
             imageio : 2.27.0
             IPython : 8.8.0
             cmocean : 2.0
          ipywidgets : 7.7.0
               scipy : 1.10.1
                tqdm : 4.64.0
              meshio : 5.0.0
          jupyterlab : 4.0.6
               trame : 3.6.2
        trame_client : 3.1.0
        trame_server : 3.0.1
           trame_vtk : 2.8.8
       trame_vuetify : 2.5.0
jupyter_server_proxy : 4.1.1-0.dev
        nest_asyncio : 1.5.5
--------------------------------------------------------------------------------
```

**Comment by akaszynski** [comment] 2024-06-11 15:06
This shouldn't operate in-place unless specifically documented to. Let's address this.

**Comment by akaszynski** [comment] 2024-06-21 17:43
@dionhaefner, notebook within zip is empty. Could you paste it (ideally as a script) here?

**Comment by dionhaefner** [comment] 2024-07-02 08:42
Oops, here's the notebook:

[pyvista_bug.ipynb.zip](https://github.com/user-attachments/files/16064975/pyvista_bug.ipynb.zip)

As far as a script goes, the one from my original post should suffice to reproduce the problem.

**Comment by akaszynski** [comment] 2024-07-02 21:11
Reproduced the bug on my end. Should be resolved in the next patch release. For the time being copy before cleaning:
```py
cleaned = grid.copy().clean()
```

BTW, this appears(!?) to be intended behavior by vtk. Per their [docs](https://vtk.org/doc/nightly/html/classvtkStaticCleanUnstructuredGrid.html#details):

> The filter does not modify the topology of the input dataset, nor change the types of cells. It may however, renumber the cell connectivity ids.

**Closed** 2024-07-03 14:26 UTC
Labels: bug
