### ISSUE TITLE
Screenshot lower left corner is chopped

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvista#130] opened 2019-03-19 03:57 UTC
The lower left corner of plots are chopped when screenshotting. This is noticeable anytime you try to add an axes widget as it's never visible in screenshots:

# Example 1

```py
import vtki
from vtki import examples

data = examples.load_airplane()

p = vtki.Plotter()
p.add_mesh(data)
p.add_axes()
p.show(screenshot='image.png')
```
Note the axes widget isn't visible:

![image](https://user-images.githubusercontent.com/22067021/54579376-cd68e000-49c8-11e9-9c36-ec7343b3f43e.png)

# Example 2
```py
import vtki
from vtki import examples

vtki.set_plot_theme('document')

plotter = vtki.Plotter(shape=(1, 2))

# Note that the (0, 0) location is active by default
# load and plot an airplane on the left half of the screen
plotter.add_text('Airplane Example\n', font_size=30)
plotter.add_mesh(examples.load_airplane(), show_edges=False)

# load and plot the uniform data example on the right-hand side
plotter.subplot(0, 1)
plotter.add_text('Uniform Data Example\n', font_size=30)
plotter.add_mesh(examples.load_uniform(), show_edges=True)

# Display the window
plotter.show(screenshot='sub-plot-demo.png')
```

Note the subplot seprators are chopped:

![sub-plot-demo](https://user-images.githubusercontent.com/22067021/54579297-6f3bfd00-49c8-11e9-9739-c2cb4e396f48.png)

**Comment by akaszynski** [comment] 2019-03-20 10:27
Both render just fine on my end.
Using:
Ubuntu 18.04
vtk==8.1.2
python 3.7.2
latest vtki

![image](https://user-images.githubusercontent.com/11981631/54677229-c219cf80-4b02-11e9-84a3-0bcb4adc7664.png)
![sub-plot-demo](https://user-images.githubusercontent.com/11981631/54677230-c219cf80-4b02-11e9-9714-61afe29a1d25.png)

**Comment by banesullivan** [comment] 2019-03-20 12:36
Can you share your screen resolution?

**Comment by akaszynski** [comment] 2019-03-20 12:56
Default window size of ``[1024, 768]``.

**Comment by akaszynski** [comment] 2019-03-20 21:33
Screenshots are clipped for me when ``offscreen=True``.

**Comment by banesullivan** [comment] 2019-03-20 21:51
Could this have to do with how the images are resized 1 or a few times when grabbing screenshots?

https://github.com/vtkiorg/vtki/blob/f0d14aabd0ef93930ea6bb992c67e17ec734ba2e/vtki/plotting.py#L1901-L1903

**Comment by akaszynski** [comment] 2019-03-21 08:50
Determined that the issue is due to the interactive renderer being disabled for off screen plotting.  The problem is, you can't enable it without either segfaulting vtk or causing the render window to flash briefly before closing (not truly off screen plotting).

The only other solution is to manually set the position, orientation, and scaling axes actor so that it behaves as it would if it was being controlled by the ``vtkOrientationMarkerWidget``.  Right now, the ``vtkOrientationMarkerWidget`` is disabled without an active interactive render window.

The border issue for the sub-plots occurs on my end regardless of the settings of ``off_screen``,

**Comment by banesullivan** [comment] 2019-03-21 17:14
> The only other solution is to manually set the position, orientation, and scaling axes actor so that it behaves as it would if it was being controlled by the vtkOrientationMarkerWidget. Right now, the vtkOrientationMarkerWidget is disabled without an active interactive render window.

That seems like an issue not worth fixing... it would likely be complicated and yield unexpected behavior - easier in my mind to simply not support that feature in off_screen mode. 

Perhaps we could implement the window flashing on screen to render everything for when we plot in IPython with a screenshot so that the axes widget appears. That's mostly where I'm concerned about it not appearing

**Closed** 2019-07-07 16:57 UTC
Labels: bug
