### ISSUE TITLE
v=0.30.1 Multiblock creation/appending is dramatically faster than v=0.32.1 when adding meshes. 

### ISSUE THREAD

**Issue by JacobBumgarner** [pyvista/pyvista#1804] opened 2021-11-15 02:11 UTC
A minimally reproducible example can be used below for testing.

``` python
import pyvista as pv
import numpy as np
from time import perf_counter as pf

def create_spline():
    line = np.random.randint(0, 100, (20, 3))
    spline = pv.Spline(line)
    tube = spline.tube(radius=1)
    return tube
    

splines = [create_spline() for _ in range(1000)]

t = pf()
block = pv.MultiBlock(splines)

mesh = block.combine()
print (pf() - t)
mesh.plot()
```

The choice of a tube mesh can be replaced here with any other mesh and the problem still persists.

**Comment by adeak** [comment] 2021-11-15 07:02
Just to cover the obvious: is vtk the same version in between? Can you show your `pv.Report()`? What timings do you get?

**Comment by JacobBumgarner** [comment] 2021-11-15 14:32
pv=0.30.1 vtk=9.0.1 time: ~1 second

**Comment by adeak** [comment] 2021-11-15 18:11
OK, thanks for the follow-up. I don't think I can reproduce your timings on debian:
  * `vtk==9.0.1`, `pyvista==0.30.1`: 248.27334477193654 seconds
  * `vtk==9.1.0`, `pyvista==0.32.1`: 168.51347969844937 seconds

So in my case the newer version is 30% faster than the old version, and I have no idea how the 1-second runtime worked.

I would be surprised if pyvista had anything mac-specific, so I'd find the vtk wheels to be a more likely culprit. Were these all pip installed things, or did you compile some packages yourself?

And finally, I would suggest comparing the other two combinations if you have the bandwidth for it, i.e. old pyvista with new vtk, and new pyvista with old vtk. These 2x2 cases would clearly show whether the change was in pyvista or vtk.

**Comment by JacobBumgarner** [comment] 2021-11-15 18:28
Wow that is very odd. Which version of python are you using?

**Comment by adeak** [comment] 2021-11-15 18:29
I normally use 3.9.2, but there are no VTK 9.0.1 wheels on pypi for python 3.9, so I switched to an older 3.8.7 for this test (which I compiled a while back myself).

**Comment by JacobBumgarner** [comment] 2021-11-15 18:33
I'm also really surprised about the huge difference in runtime between your and my computers. I'm using a MPB 2019 15", so nothing crazy powerful.

Using pyvista==0.30.1 and vtk==9.1.0 still produces ~ 1 second runtime
Using pyvista==0.32.1 and vtk==9.0.1 still produces ~ 100 second runtime.

So whatever is happening with the PyVista package on my end is clearly causing problems. Also glad to hear that it's not a python version issue. 

And to answer your earlier question, I'm using pip installations with pyenv as my environment manager. 

Would you mind sharing your pv.Report() with me?

**Comment by adeak** [comment] 2021-11-15 18:49
Hold on, something's weird here. I recreated the environment and the timing script from scratch to answer your question... and now I get 0.1 second runtime with the old setup! And I see scalars, which weren't there before. Weird. I'm starting to think I messed up something in my environment during my first attempt... sorry about that.

For the sake of exactness:

Old setup
```
--------------------------------------------------------------------------------
  Date: Mon Nov 15 19:39:20 2021 CET

                OS : Linux
            CPU(s) : 8
           Machine : x86_64
      Architecture : 64bit
       Environment : Python
        GPU Vendor : Intel
      GPU Renderer : Mesa Intel(R) UHD Graphics 620 (WHL GT2)
       GPU Version : 4.6 (Core Profile) Mesa 20.3.5

  Python 3.8.7 (default, Jan 27 2021, 23:12:13)  [GCC 10.2.1 20210110]

           pyvista : 0.30.1
               vtk : 9.0.1
             numpy : 1.21.4
           imageio : 2.10.4
           appdirs : 1.4.4
            scooby : 0.5.7
            meshio : 4.4.6
--------------------------------------------------------------------------------
```
Runtime 0.1 second.

Newer setup, only updating pyvista:
```
--------------------------------------------------------------------------------
  Date: Mon Nov 15 19:44:49 2021 CET

                OS : Linux
            CPU(s) : 8
           Machine : x86_64
      Architecture : 64bit
       Environment : Python
        GPU Vendor : Intel
      GPU Renderer : Mesa Intel(R) UHD Graphics 620 (WHL GT2)
       GPU Version : 4.6 (Core Profile) Mesa 20.3.5

  Python 3.8.7 (default, Jan 27 2021, 23:12:13)  [GCC 10.2.1 20210110]

           pyvista : 0.32.1
               vtk : 9.0.1
             numpy : 1.21.4
           imageio : 2.10.4
           appdirs : 1.4.4
            scooby : 0.5.7
            meshio : 4.4.6
--------------------------------------------------------------------------------
```
Runtime 240 seconds.

I checked pyvista 0.31.1 as a first step of bisecting, and it's also fast (even slightly faster than the oldest version). So this indeed on our side, thanks for finding it. I'll track down the change that broke this.

As an aside I wouldn't be too surprised at different runtimes, because my laptop isn't very strong either, and it doesn't have a discrete GPU.

**Comment by adeak** [comment] 2021-11-15 18:57
This was broken by https://github.com/pyvista/pyvista/pull/1593/. I'm not very happy about this, because that was a major PR with 2800 lines lines touched across 57 files :cold_sweat:

I'll try to figure out what's off here. The fact that scalars are missing are a good sign I think. And in any case MultiBlocks are more of less localised.

**Comment by JacobBumgarner** [comment] 2021-11-15 19:00
Awesome, I'm glad that you can reproduce this at least. I was really starting to question my entire environment setup lol. 

And I that there were a TON of changes in the recent update. I started trying to dig through it a little but, but I had to sleep and gave up.

**Comment by adeak** [comment] 2021-11-15 19:02
Aaaaah I know what this is!

After https://github.com/pyvista/pyvista/pull/1593:
```py
>>> import pyvista as pv
>>> pv.Sphere() == pv.Sphere()
True
```

Preceding commit:
```py
>>> import pyvista as pv
>>> pv.Sphere() == pv.Sphere()
False
```

In between [`__eq__` was implemented for datasets](https://github.com/pyvista/pyvista/blob/e31c2a6d51dafee59dbe601d13e89b03413c95fe/pyvista/core/dataobject.py#L224-L246). This recurses into the attributes of meshes, which ends up being slow if you do it a lot of times. I bet MultiBlock creation triggers this for each submesh for whatever reason.

**Comment by JacobBumgarner** [comment] 2021-11-15 19:07
So quick to identify this. Is there anything I can do to help?

**Comment by adeak** [comment] 2021-11-15 19:17
> So quick to identify this.

To be fair I haven't proven it yet, but it's a very very good guess :)

> Is there anything I can do to help?

Probably not, but the fact that you've flagged this is already huge help for us :) Thank you.

Looking at the implementation of MultiBlock, there are multiple things that jump out at me. When you initialise a MultiBlock from a sequence of meshes, `.append` is called with each mesh. In turn this does `self[index] = block`, which calls `__setitem__`.

However `__setitem__` ends with https://github.com/pyvista/pyvista/blob/828fa349134e036efac9f47852a1bed4bf51c929/pyvista/core/composite.py#L471-L472

Note that [`self.refs` is a list](https://github.com/pyvista/pyvista/blob/828fa349134e036efac9f47852a1bed4bf51c929/pyvista/core/composite.py#L83). So first we do an `O(n)` sweep over the list to see if the new data is in there. Then if it's _not_ in there, we call `append`. Then at the end of `MultiBlock.append` we do that again... https://github.com/pyvista/pyvista/blob/828fa349134e036efac9f47852a1bed4bf51c929/pyvista/core/composite.py#L336-L337

And there has to be one more leak here:
```py
>>> import pyvista as pv
>>> mb = pv.MultiBlock([pv.Sphere()])
>>> len(mb.refs)
3
```
The first two items are the mesh itself, and the third item is the mesh in a one-element tuple...

So there's a lot of cruft in the implementation, and now that membership comparison triggers the new heavy `__eq__` instead of `object.__eq__` which was blasing-fast based on `self is other`, this is becoming obvious. We'll have to refactor `MultiBlock` to fix this.

**Comment by JacobBumgarner** [comment] 2021-11-15 19:35
Great. I'll keep an eye out for the updated implementation whenever it comes!

**Comment by adeak** [comment] 2021-11-15 19:44
First take: https://github.com/pyvista/pyvista/pull/1805. We should get this right so I don't expect it to be merged too soon. We'll have to make sure we're not breaking something or missing important corner cases.

**Comment by adeak** [comment] 2021-11-15 19:52
Oh, and scalars are still missing. I haven't checked this yet, it might just be that on the new versions the scalars are not automatically set as active. This might actually be a regression, but if this is the case then one can just activate them manually. Still, we should probably get around to poking that change too.

**Closed** 2021-12-08 07:01 UTC
Labels: bug, review-critical
