### ISSUE TITLE
Confused about boundary edges 

### ISSUE THREAD

**Issue by darikg** [pyvista/pyvista#1301] opened 2021-05-06 22:10 UTC
Apologies in advance if I'm missing something really obvious here. A cylinder and an ellipsoid are both closed manifolds and shouldn't have boundary edges, right?

```python
from pyvista import *

def plot_boundary_edges(mesh):
    mesh.extract_feature_edges(
        boundary_edges=True,
        non_manifold_edges=False, 
        feature_edges=False, 
        manifold_edges=False, 
        inplace=False,
    ).plot(window_size=(200, 200))

plot_boundary_edges(Cylinder())
plot_boundary_edges(ParametricEllipsoid())
```

Triangulating either mesh beforehand doesn't help.

![b edges](https://user-images.githubusercontent.com/6875882/117371398-d3b2c280-ae95-11eb-88fd-e90d3b5ddca3.PNG)

-----
```txt
--------------------------------------------------------------------------------
  Date: Thu May 06 18:07:16 2021 Eastern Daylight Time

                OS : Windows
            CPU(s) : 8
           Machine : AMD64
      Architecture : 64bit
               RAM : 15.8 GB
       Environment : Jupyter
        GPU Vendor : Intel
      GPU Renderer : Intel(R) UHD Graphics
       GPU Version : 4.5.0 - Build 27.20.100.8729

  Python 3.7.9 | packaged by conda-forge | (default, Feb 13 2021, 19:28:53)
  [MSC v.1916 64 bit (AMD64)]

           pyvista : 0.29.0
               vtk : 8.2.0
             numpy : 1.19.2
           imageio : 2.9.0
           appdirs : 1.4.4
            scooby : 0.5.6
            meshio : 4.3.8
        matplotlib : 3.3.4
             PyQt5 : Version unknown
           IPython : 7.21.0
          colorcet : 1.0.0
             scipy : 1.6.1
        itkwidgets : 0.32.0
              tqdm : 4.59.0

  Intel(R) Math Kernel Library Version 2020.0.4 Product Build 20200917 for
  Intel(R) 64 architecture applications
--------------------------------------------------------------------------------

```

**Comment by adeak** [comment] 2021-05-23 23:58
So this is interesting. Both meshes are created using vtk, so this is probably not our fault. But it turns out that these objects are not very clean:
```py
>>> import pyvista as pv
>>> cylinder = pv.Cylinder()
>>> cleaned = cylinder.clean()
>>> cylinder.n_points, cleaned.n_points
(400, 200)
>>> cylinder.n_open_edges, cleaned.n_open_edges
(400, 0)
```

A cylinder has 100 points along its cap by default, which gives us 200 points total. For some reason our cylinders start with 400 points, and the excess contributes to the open edges. If we `clean()` the mesh the 200 spurious points disappear, and so do all the open edges.

Unfortunately the parametric ellipsoid can't be fixed this easily:
```py
>>> ellipsoid = pv.ParametricEllipsoid()
>>> cleaned = ellipsoid.clean()
>>> ellipsoid.n_open_edges, cleaned.n_open_edges
(396, 94)
```
My bet would be that the 94 points are along half a great circle, i.e. the "seam" where the ellipsoid should close up. Which could make this harder to close.

We can add a finite tolerance to get rid of the remaining edges:
```py
>>> ellipsoid = pv.ParametricEllipsoid()
>>> cleaned = ellipsoid.clean(tolerance=1e-10)
>>> ellipsoid.n_open_edges, cleaned.n_open_edges
(396, 0)
```

I don't know if there's anything we can do about this in pyvista for general cases. Perhaps we could call `clean` at the end of our utilities to get rid of some of the ugliness, although the result might end up a bit weirder. For the case of the parametric ellipsoid, for instance, the original contiguous open edges become a scattered group of shorter great circle sections after cleaning unless we set a small tolerance. But choosing hard-coded "small" values can go very wrong if meshes with unexpecte parameters are created.

@akaszynski do you think we can tackle this in pyvista?

**Comment by adeak** [comment] 2021-05-24 00:16
Looking at [the VTK source](https://gitlab.kitware.com/vtk/vtk/-/blob/master/Filters/Sources/vtkCylinderSource.cxx) the issue is straightforward: for a capped cylinder the sides and the circular caps are generated independently, so the cap points will indeed be duplicated. And cleaning the mesh on our end will merge these points together, properly closing the surface.

I suspect that for the ellipsoid there are floating-point inaccuracies which make the start and end points along the seam differ a bit, but due to the size of the machine epsilon we're talking about small differences (which is why a tolerance of `1e-10` fixed it).

**Closed** 2021-09-20 21:53 UTC
Labels: bug, vtk-issue
