### ISSUE TITLE
Boolean_intersection when one mesh is included in the other

### ISSUE THREAD

**Issue by nicdall** [pyvista/pyvista#3840] opened 2023-01-18 16:05 UTC
### Describe the bug, what's wrong, and what you expected.

Hello,

I am having issues with the boolean intersection filter : when trying to compute the intersection of two meshes, when one is included in the other, the resulting mesh is empty, instead of returning the smaller mesh as a result. 

### Steps to reproduce the bug.

```python
import pyvista as pv

a = pv.Cube(x_length=2, y_length=2, z_length=2).triangulate()
b = pv.Cube().triangulate() # smaller cube (x_length=1)

r = a.boolean_intersection(b)
r
```

The result I get is the following:

PolyData (0x125a516c700)
  N Cells:	0
  N Points:	0
  N Strips:	0
  X Bounds:	1.000e+299, -1.000e+299
  Y Bounds:	1.000e+299, -1.000e+299
  Z Bounds:	1.000e+299, -1.000e+299
  N Arrays:	2

I would expect to get the smaller mesh, b, instead:

PolyData (0x125a7b5e500)
  N Cells:	12
  N Points:	8
  N Strips:	0
  X Bounds:	-5.000e-01, 5.000e-01
  Y Bounds:	-5.000e-01, 5.000e-01
  Z Bounds:	-5.000e-01, 5.000e-01
  N Arrays:	3

### System Information

```shell
--------------------------------------------------------------------------------
  Date: Wed Jan 18 16:54:16 2023 Romance Standard Time
                OS : Windows
            CPU(s) : 8
           Machine : AMD64
      Architecture : 64bit
               RAM : 15.9 GiB
       Environment : IPython
        GPU Vendor : Intel
      GPU Renderer : Intel(R) UHD Graphics 620
       GPU Version : 4.5.0 - Build 30.0.101.1338
  Python 3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:16:33) [MSC
  v.1929 64 bit (AMD64)]
           pyvista : 0.37.0
               vtk : 9.2.2
             numpy : 1.23.5
           imageio : 2.22.4
            scooby : 0.7.0
             pooch : v1.6.0
        matplotlib : 3.6.2
             PyQt5 : 5.15.7
           IPython : 8.7.0
        ipyvtklink : 0.2.3
             scipy : 1.9.3
--------------------------------------------------------------------------------
```

**Comment by akaszynski** [comment] 2023-02-01 06:01
That's indeed unintended behavior, and I've opened #3929 to help address it.

I'm afraid it's not going to get fixed in PyVista, the best we can do is provide a slightly more helpful error message. VTK's boolean filter has many known issues and I recommend taking a look at https://github.com/zippy84/vtkbool if you need a more reliable filter.

**Closed** 2023-02-01 15:21 UTC
Labels: bug
