### ISSUE TITLE
Crash after closing figure window

### ISSUE THREAD

**Issue by alexdaniilidis** [pyvista/pyvista#500] opened 2019-12-13 10:08 UTC
Trying to visualize a 3D dataset with an orthogonal grid. Everything works as expected. Plot appears and is interactive. Closing the plot either from the window or with q gives the error below and kernel becomes unresponsive. Only solution is to restart kernel. After restaring the problem persists

Running on Spyder 4.0.0 with Python 3.7, win10
Sys version: 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)]
Spyder uses the QT5 backend (default) for graphics.

-----

**To Reproduce**

```py
import numpy as np
import discretize
import pyvista


ncx = 15      # number of core mesh cells in x
ncy = 15      # number of core mesh cells in y
ncz = 15      # number of core mesh cells in y
dx = 15       # base cell width x
dy = 15       # base cell width y
dz = 1        # base cell width z
npad_x = 0    # number of padding cells in x
npad_y = 0    # number of padding cells in y
npad_z = 0    # number of padding cells in z
exp_x = 1.25  # expansion rate of padding cells in x
exp_y = 1.25  # expansion rate of padding cells in y
exp_z = 1.25  # expansion rate of padding cells in z

hx = [(dx, npad_x, -exp_x), (dx, ncx), (dx, npad_x, exp_x)]
hy = [(dy, npad_y, -exp_y), (dy, ncy), (dy, npad_y, exp_y)]
hz = [(dz, npad_z, -exp_z), (dz, ncz), (dz, npad_z, exp_z)]

mesh = discretize.TensorMesh([hx, hy, hz])
vals = np.random.randint(1, 1000, mesh.nC)

dataset = mesh.toVTK({'myvals':vals})

p = pyvista.Plotter(notebook=False)
p.show_grid()

xyz = (200,112.5,7.5)
p.add_mesh_slice_orthogonal(dataset)
p.show()
```

**Screenshots**
![PyVista_error](https://user-images.githubusercontent.com/34479636/70791700-de981f00-1d97-11ea-9b3b-07d2770293e2.PNG)

**System Information:**
--------------------------------------------------------------------------------
  Date: Fri Dec 13 10:56:25 2019 W. Europe Standard Time

           Windows : OS
                 8 : CPU(s)
             AMD64 : Machine
             64bit : Architecture
           31.9 GB : RAM
           Jupyter : Environment

  Python 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)]

            0.22.4 : pyvista
             8.1.2 : vtk
            1.17.4 : numpy
             2.6.1 : imageio
             1.4.3 : appdirs
             0.4.3 : scooby
             3.1.1 : matplotlib
             5.9.2 : PyQt5
            7.10.1 : IPython
             7.5.1 : ipywidgets

  Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for
  Intel(R) 64 architecture applications

--------------------------------------------------------------------------------

```

**Comment by GuillaumeFavelier** [comment] 2019-12-13 13:36
I think it's a duplicate of #186

**Comment by GuillaumeFavelier** [comment] 2019-12-13 13:39
Meanwhile, maybe you could try the `BackgroundPlotter` instead?

Also, do you mean:

```diff
  ...
  xyz = (200,112.5,7.5)
+ p.add_mesh(dataset.slice_orthogonal())
- p.add_mesh_slice_orthogonal(dataset)
  p.show()
```

**Comment by alexdaniilidis** [comment] 2019-12-13 14:42
Thanks for the feedback and suggestion. 

for the syntax, 
`p.add_mesh_slice_orthogonal(dataset)`
seemed to work fine and behaving as expected. Am i missing something?

**Comment by GuillaumeFavelier** [comment] 2019-12-13 14:49
Whoops! Everything is fine, I missed [this function in the documentation](https://docs.pyvista.org/plotting/plotting.html?highlight=slice_orthogonal#pyvista.BasePlotter.add_mesh_slice_orthogonal), my bad.

**Comment by banesullivan** [comment] 2019-12-14 20:31
@alexdaniilidis, this should be fixed in #502 - If you have the time, it'd be great if you could check out that branch and see if your issues are resolved.

**Comment by alexdaniilidis** [comment] 2019-12-16 11:12
@banesullivan i have tried after installing pyvista with 
`pip install git+https://github.com/pyvista/pyvista.git@refs/pull/502/head`

behavior is still the same with error:root:#version 120 and python crashing

anything else i could try?

**Comment by banesullivan** [comment] 2019-12-16 14:11
@GuillaumeFavelier, can you reproduce this on that branch? I can’t 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by GuillaumeFavelier** [comment] 2019-12-16 14:47
I tried the [given snippet](https://github.com/pyvista/pyvista/issues/500#issue-537459287) on #502 with `spyder` and when I close the window I don't have the `Shader error` anymore. Instead I obtain the expected following message:

![image](https://user-images.githubusercontent.com/18143289/70916019-398d7880-201b-11ea-8f0e-0045f0f878ef.png)

**Comment by banesullivan** [comment] 2019-12-16 16:42
Hm was that pip command correct for @alexdaniilidis 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by alexdaniilidis** [comment] 2019-12-16 17:10
what would be the rigth pip command to install 502?

**Comment by alexdaniilidis** [comment] 2019-12-16 17:10
what would be the right pip command to install 502?

**Comment by banesullivan** [comment] 2019-12-16 17:15
It looks fine to me, but can you try the following just to be sure

```
pip install git+https://github.com/pyvista/pyvista.git@patch/win-exit
```

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by alexdaniilidis** [comment] 2019-12-17 12:16
@banesullivan with the provided pip command i no longe hace the issue. 
I can plot, interact with the plot and close without crashing. I can then re-plot the figure etc. 
Works as expected and as shown by @GuillaumeFavelier 
Thanks for the help!

**Closed** 2019-12-17 15:20 UTC
Labels: bug, duplicate
