### ISSUE TITLE
2D streamline example failing with pythreejs notebook backend

### ISSUE THREAD

**Issue by charithjeewantha** [pyvista/pyvista#3439] opened 2022-10-10 21:47 UTC
### Describe the bug, what's wrong, and what you expected.

I was trying the 2D streamline tutorial from [here](https://docs.pyvista.org/examples/01-filter/streamlines_2D.html#sphx-glr-download-examples-01-filter-streamlines-2d-py) 

But the images are not displayed. 
I'm running the a Jupyter notebook through docker in my Windows computer (Because I'm learning [FEniCSx](https://fenicsproject.org/) through that)

You get an error:
```
/usr/local/lib/python3.10/dist-packages/pyvista/jupyter/pv_pythreejs.py:436: UserWarning: Empty or unsupported dataset attached to actor
  warnings.warn('Empty or unsupported dataset attached to actor')
```

### Steps to reproduce the bug.

```

from pyvista import set_plot_theme
set_plot_theme('document')

import pyvista as pv
from pyvista import examples
pv.set_jupyter_backend("pythreejs")

mesh = examples.download_cylinder_crossflow()
fluid_mesh = mesh[0]
print(fluid_mesh)

one_streamline = fluid_mesh.streamlines(
    start_position=(0.0, 0.4, 0.0),
    max_time=100.0,
    compute_vorticity=False,  # vorticity already exists in dataset
)

clim = [0, 20]
camera_position = [(7, 0, 20.0), (7, 0.0, 0.0), (0.0, 1.0, 0.0)]

p = pv.Plotter()
for i in range(1, len(mesh)):
    p.add_mesh(mesh[i], color='k')
p.add_mesh(one_streamline.tube(radius=0.05), scalars="vorticity_mag", clim=clim)
p.view_xy()
p.show(cpos=camera_position)
```

### System Information

```shell
--------------------------------------------------------------------------------
  Date: Mon Oct 10 21:09:57 2022 UTC

                OS : Linux
            CPU(s) : 8
           Machine : x86_64
      Architecture : 64bit
               RAM : 7.6 GiB
       Environment : Jupyter
       GPU Details : error

  Python 3.10.4 (main, Jun 29 2022, 12:14:53) [GCC 11.2.0]

           pyvista : 0.36.1
               vtk : 9.2.0
             numpy : 1.22.4
           imageio : 2.21.1
           appdirs : 1.4.4
            scooby : 0.5.12
        matplotlib : 3.5.3
           IPython : 8.4.0
             scipy : 1.9.0
              tqdm : 4.64.1
        jupyterlab : 3.4.5
         pythreejs : Version unknown
--------------------------------------------------------------------------------
```

### Screenshots

https://user-images.githubusercontent.com/81730478/194957160-e4cbfd07-1fc8-4625-b2b4-25ccdc018278.mp4

**Comment by banesullivan** [comment] 2022-10-11 04:52
Well, this is odd. As far as I can tell, you are just running [the example](https://docs.pyvista.org/examples/01-filter/streamlines_2D.html) as is -- *but* with the `pythreejs` notebook rendering backend.

For some reason, this is failing just with the `pythreejs` backend enabled. I have been encountering many problems with this backend lately and have mentioned in other issues lately that we do not plan to support that backend long-term (we're working on a first-class notebook rendering backend develop for and by PyVista though this has yet to materialize at this time).

Could you try using another of the currently available rendering backends? Perhaps the `ipyvtklink` backend? ref https://docs.pyvista.org/user-guide/jupyter/ipyvtk_plotting.html

**Comment by charithjeewantha** [comment] 2022-10-12 04:48
> Well, this is odd. As far as I can tell, you are just running [the example](https://docs.pyvista.org/examples/01-filter/streamlines_2D.html) as is -- _but_ with the `pythreejs` notebook rendering backend.
> 
> For some reason, this is failing just with the `pythreejs` backend enabled. I have been encountering many problems with this backend lately and have mentioned in other issues lately that we do not plan to support that backend long-term (we're working on a first-class notebook rendering backend develop for and by PyVista though this has yet to materialize at this time).
> 
> Could you try using another of the currently available rendering backends? Perhaps the `ipyvtklink` backend? ref https://docs.pyvista.org/user-guide/jupyter/ipyvtk_plotting.html

Thank you for the response! Yes it worked!

**Comment by charithjeewantha** [comment] 2022-10-12 04:48
> Well, this is odd. As far as I can tell, you are just running [the example](https://docs.pyvista.org/examples/01-filter/streamlines_2D.html) as is -- _but_ with the `pythreejs` notebook rendering backend.
> 
> For some reason, this is failing just with the `pythreejs` backend enabled. I have been encountering many problems with this backend lately and have mentioned in other issues lately that we do not plan to support that backend long-term (we're working on a first-class notebook rendering backend develop for and by PyVista though this has yet to materialize at this time).
> 
> Could you try using another of the currently available rendering backends? Perhaps the `ipyvtklink` backend? ref https://docs.pyvista.org/user-guide/jupyter/ipyvtk_plotting.html

Thank you very much for the response. Yes it worked!

**Comment by zou000** [comment] 2022-12-26 00:29
Probably related to Tube(): #3752

**Comment by banesullivan** [comment] 2022-12-26 01:39
This is definitely related and caused by #3752 - thank you for tracking it down to a simpler example!

**Comment by banesullivan** [comment] 2022-12-26 01:39
I'm going to close this issue in favor of #3752

**Closed by banesullivan** 2022-12-26 01:39 UTC
Labels: bug
