### ISSUE TITLE
JS Error related to vue2 using Trame in Pyvista

### ISSUE THREAD

**Issue by Jimmy-KL** [pyvista/pyvista#5513] opened 2024-01-25 03:08 UTC
### Describe the bug, what's wrong, and what you expected.

When I tried to run example[ ui_template.py](https://github.com/pyvista/pyvista/blob/main/examples_trame/basic/ui_template.py), I got a JS Error called `JS Error => error: Uncaught TypeError: r.a.extend is not a function`.
If I change everything to vue3, it works. But the standard widgets (buttons) in `plotter_ui `will not show unless we set the VContainer style to "position: relative" - `style="position: relative"`.

### Steps to reproduce the bug.

This example is old and we need to change code line 18 to `server = get_server(client_type="vue2")` at first. 

### System Information

```shell
OS : Windows
            CPU(s) : 16
           Machine : AMD64
      Architecture : 64bit
       Environment : Python
        GPU Vendor : Intel
      GPU Renderer : Intel(R) UHD Graphics
       GPU Version : 4.5.0 - Build 31.0.101.1999
  MathText Support : False

  Python 3.12.1 | packaged by conda-forge | (main, Dec 23 2023, 07:53:56) [MSC
  v.1937 64 bit (AMD64)]

           pyvista : 0.43.2
               vtk : 9.2.6
             numpy : 1.26.3
        matplotlib : 3.8.2
            scooby : 0.9.2
             pooch : 1.8.0
            pillow : 10.2.0
            meshio : 5.3.4
             trame : 3.5.1
      trame_client : 2.14.2
      trame_server : 2.15.0
         trame_vtk : 2.6.3
     trame_vuetify : 2.3.1

  Intel(R) oneAPI Math Kernel Library Version 2023.1-Product Build 20230303
  for Intel(R) 64 architecture applications
```

**Comment by jourdain** [comment] 2024-01-26 18:37
The JS error is because you switch between vue2/vue3 client and your browser cache the previous client. You need to clear your browser cache or use the same port for vue2 and another one for vue3 ones.

The other is a duplicate of https://github.com/pyvista/pyvista/issues/5430

**Comment by jourdain** [comment] 2024-01-26 22:44
I may have referenced the wrong bug. But that bug (relative) has been fixed in master.

**Comment by Jimmy-KL** [comment] 2024-01-27 01:03
@jourdain Yes, after clearing the cache, it's working. And there is another small problem you can check it - 

> When using vue3, the standard widgets (buttons) in plotter_ui will not show unless we set the VContainer style to "position: relative" - style="position: relative". But in vue2, there is no need to add this parameter.

**Comment by jourdain** [comment] 2024-01-27 23:42
Like I said, that small problem is already fixed and merged into master but is not yet include in a PyVista release.

**Closed** 2024-01-28 08:40 UTC
Labels: bug
