### ISSUE TITLE
Some Doc figures broken

### ISSUE THREAD

**Issue by AndrewAnnex** [pyvista/pyvista#1543] opened 2021-07-26 17:32 UTC
I was reading the docs for https://docs.pyvista.org/examples/01-filter/clipping-with-surface.html?highlight=clip and I noticed some of the figures appear empty, just showing the colorbars/labels but not the actual meshes. for example:
![empty](https://docs.pyvista.org/_images/sphx_glr_clipping-with-surface_003.png)

**Comment by akaszynski** [comment] 2021-07-27 17:41
Issue is caused by our virtual framebuffer being unable to render docs correctly.  Will be fixed in the next release when we manually regenerate the docs.

**Comment by tkoyama010** [comment] 2021-08-02 06:37
Ref https://dev.pyvista.org/examples/01-filter/clipping-with-surface.html?highlight=clip

**Closed by tkoyama010** 2021-08-02 06:37 UTC
