### ISSUE TITLE
SegFault when closing session after pyvista.plot

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvista#558] opened 2020-01-22 17:55 UTC
**Describe the bug, what's wrong, and what you expect:**

After plotting and exiting a Python session, a segfault occurs. See output from bash below

-----

**To Reproduce**

```py
(dev) ➜  pyvista git:(master) python
Python 3.7.3 | packaged by conda-forge | (default, Dec  6 2019, 08:36:57)
[Clang 9.0.0 (tags/RELEASE_900/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyvista as pv
>>> pv.Sphere().plot()
[(1.014693063938463, 1.3721835511497151, 2.8672508897437536),
 (0.0, 0.0, 0.0),
 (-0.6903521188359678, -0.5264483112597669, 0.49625208069128485)]
>>> exit()
[1]    17751 segmentation fault  python
(dev) ➜  pyvista git:(master)
```

-----

**System Information:**
 Please run the following code wherever you are experiencing the bug and paste the output below. This report helps us track down bugs and it is critical to addressing your bug:

```py
# Get system info
import pyvista as pv
print(pv.Report())
```

(On `master` branch) 

```txt

--------------------------------------------------------------------------------
  Date: Wed Jan 22 10:52:07 2020 MST

            Darwin : OS
                12 : CPU(s)
            x86_64 : Machine
             64bit : Architecture
           32.0 GB : RAM
            Python : Environment
        GPU Vendor : ATI Technologies Inc.
      GPU Renderer : AMD Radeon Pro Vega 20 OpenGL Engine
       GPU Version : 4.1 ATI-3.4.19

  Python 3.7.3 | packaged by conda-forge | (default, Dec  6 2019, 08:36:57)
  [Clang 9.0.0 (tags/RELEASE_900/final)]

            0.23.0 : pyvista
             8.2.0 : vtk
            1.17.3 : numpy
             2.6.1 : imageio
             1.4.3 : appdirs
             0.5.0 : scooby
             3.1.2 : matplotlib
            5.12.3 : PyQt5
             7.6.1 : IPython
             1.0.0 : colorcet
               2.0 : cmocean
--------------------------------------------------------------------------------
```

**Comment by banesullivan** [comment] 2020-01-22 17:56
This appears to be fine on the last release, but `master` is having this segfault issue

**Comment by GuillaumeFavelier** [comment] 2020-01-22 17:58
Does it happen consistently? Interestingly I got a crash on [Circle](https://travis-ci.org/pyvista/pyvista/jobs/640547699#L1024-L1028) on https://github.com/pyvista/pyvista/pull/548. You think it could be related?

**Comment by GuillaumeFavelier** [comment] 2020-01-22 18:01
Otherwise you can ignore my comment, I modified a lot of things anyway.

**Comment by banesullivan** [comment] 2020-01-22 18:52
Every time I try with that code above, it segfaults (on Mac). What weirds me out is that just doing `pv.Report()` (which makes a plotter and adds a sphere) has no issue/segfault. The only difference is that the Report plotting is done off-screen. So I tried:

```py
(dev) ➜  pyvista git:(master) python
Python 3.7.3 | packaged by conda-forge | (default, Dec  6 2019, 08:36:57)
[Clang 9.0.0 (tags/RELEASE_900/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyvista as pv
>>> pv.Sphere().plot(off_screen=True)
[(1.9264490110725325, 1.9264490110725325, 1.9264490110725325),
 (0.0, 0.0, 0.0),
 (0.0, 0.0, 1.0)]
>>> exit()
(dev) ➜  pyvista git:(master)
``` 

and all is good with off-screen plotting. All the CIs should be doinng things off screen, so they shouldn't be picking up on this.

Also, I have a gut feeling this is related to #526 which is super flaky

**Comment by banesullivan** [comment] 2020-01-22 18:58
And I loaded up the Linux VM I have and it happened there too:

```py
➜  pyvista python
Python 3.6.8 (default, Jan 14 2019, 11:02:34) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyvista as pv
>>> pv.__file__
'/mnt/hgfs/bane/Software/pyvista/pyvista/pyvista/__init__.py'
>>> pv.Sphere().plot()
[(1.142549149081754, 2.104652900294744, 2.32349628534252),
 (0.0, 0.0, 0.0),
 (-0.4970506092294406, -0.5073262033524568, 0.7039608051991413)]
>>> exit()
[1]    29592 segmentation fault (core dumped)  python3
➜  pyvista
```

**Comment by banesullivan** [comment] 2020-01-22 18:59
Hmmm... maybe it's just the `pyvista.plot` routine... as the following is fine:

```py
(dev) ➜  pyvista git:(master) python
Python 3.7.3 | packaged by conda-forge | (default, Dec  6 2019, 08:36:57)
[Clang 9.0.0 (tags/RELEASE_900/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyvista as pv
>>> p = pv.Plotter()
>>> p.add_mesh(pv.Sphere())
(vtkRenderingOpenGL2Python.vtkOpenGLActor)0x7fe14a613a68
>>> p.show()
[(1.6490062489111579, 2.878138134982162, -0.3615475678252341),
 (0.0, 0.0, 0.0),
 (0.05511968644852824, 0.09329844242956611, 0.9941112718433651)]
>>> exit()
(dev) ➜  pyvista git:(master)
```

**Comment by banesullivan** [comment] 2020-01-22 19:12
oooo another time, I got an ectual message:

```py
(dev) ➜  pyvista git:(master) ✗ python
Python 3.7.3 | packaged by conda-forge | (default, Dec  6 2019, 08:36:57)
[Clang 9.0.0 (tags/RELEASE_900/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyvista as pv
>>> pv.Sphere().plot()
[(0.7760908563208468, 3.2274188947768723, -0.3392162100481589),
 (0.0, 0.0, 0.0),
 (-0.14933921711545484, 0.1388080081417365, 0.9789944510093337)]
>>> exit()
python(18661,0x116fa0dc0) malloc: *** error for object 0x7fe3dbc76830: pointer being freed was not allocated
python(18661,0x116fa0dc0) malloc: *** set a breakpoint in malloc_error_break to debug
[1]    18661 abort      python
(dev) ➜  pyvista git:(master)
```

**Comment by GuillaumeFavelier** [comment] 2020-01-22 22:23
I investigated the `plot()` function and the segfault happens when `auto_close=True` because of `plotter.close()`.

Also I noticed that if I comment the [line 2554 of plotting.py](https://github.com/pyvista/pyvista/blob/master/pyvista/plotting/plotting.py#L2554), it does not segfault anymore: 

```py
    def close(self):
        """Close the render window."""
        # must close out widgets first
        super(BasePlotter, self).close()
...
        if hasattr(self, 'iren'):
            # self.iren.RemoveAllObservers() <<<<<< why?
            self.iren.TerminateApp()
            del self.iren
...
```

But I don't know why it stops crashing.

**Comment by banesullivan** [comment] 2020-01-23 04:58
That is *really* weird... From looking at the diff with `0.23.0`, no new observers were added (I think). Maybe when trying to remove an observer, it's trying to destroy an object we already cleaned up?..

**Comment by ssssOO** [comment] 2020-01-23 08:48
I don't know if my issue is related, but whenever I close a window created with the show function of the Plotter object there is a weird error in the output:

 X Error of failed request:  BadDrawable (invalid Pixmap or Window parameter)
  Major opcode of failed request:  130 (MIT-SHM)
  Minor opcode of failed request:  3 (X_ShmPutImage)
  Resource id in failed request:  0x4200002
  Serial number of failed request:  27
  Current serial number in output stream:  28

The program crashes completely after closing the window. There are also core dump files written so I could try to send you those files (they are around 100mB...)

**Comment by GuillaumeFavelier** [comment] 2020-01-23 12:41
Well, I thought it was related to `plot()`. And does it happen consistently?

Could you share a small code snippet that reproduces your experience @ssssOO ? I don't feel like swimming into 100MB dump xD

**Comment by ssssOO** [comment] 2020-01-23 13:03
Just a simple script like

```
import pyvista
p = pyvista.Plotter()
sphere = pyvista.Sphere()
p.add_mesh(sphere)
p.show()
```
Executed in a terminal as

`python script.py`

Triggers the following error when the window is closed

```
X Error of failed request:  BadDrawable (invalid Pixmap or Window parameter)
  Major opcode of failed request:  130 (MIT-SHM)
  Minor opcode of failed request:  3 (X_ShmPutImage)
  Resource id in failed request:  0x4200002
  Serial number of failed request:  19
  Current serial number in output stream:  20
```

I have tried running the same code in an interactive terminal (as @banesullivan) and the same error occurs. I don't know why are those core dumps so big. It is also worth noting that I'm using some kind of X-Server interface so it might be completely unrelated to @banesullivan issues.

To help the debugging process, I have tried the QT windows code snippet found in:

> https://docs.pyvista.org/plotting/qt_plotting.html

With this code I'm capable of closing the QT window without errors. It seems weird in my opiniong as the `Plotter` implementation is similat to the `MainWindow` object implementation of the code snippet of the previous link

**Comment by GuillaumeFavelier** [comment] 2020-01-23 18:19
> I'm using some kind of X-Server interface

Interesting. @ssssOO would you mind sharing a `pyvista.Report()` like @banesullivan did above? I'm still not sure this is related but it is worth noting for sure.

**Comment by ssssOO** [comment] 2020-01-24 11:03
Bien sûr :)

```
--------------------------------------------------------------------------------
  Date: Fri Jan 24 11:52:32 2020 CET

             Linux : OS
                24 : CPU(s)
            x86_64 : Machine
             64bit : Architecture
          754.6 GB : RAM
            Python : Environment

  Python 3.7.0 (default, Jun 28 2018, 13:15:42)  [GCC 7.2.0]

            0.23.0 : pyvista
             8.1.2 : vtk
            1.15.1 : numpy
             2.4.1 : imageio
             1.4.3 : appdirs
             0.4.3 : scooby
             2.2.3 : matplotlib
            5.14.1 : PyQt5
             6.5.0 : IPython

  Intel(R) Math Kernel Library Version 2019.0.0 Product Build 20180829 for
  Intel(R) 64 architecture applications
```

I have tried with other versions of PyQt5 but I see the same crashes.

I have tried the same code in Windows and it works, so there must be some issue with CentOS/linux. However, it is really weird that there is no error when using the Qt example of your website but there are errors when using the default `Plotter` object...

**Comment by banesullivan** [comment] 2020-01-27 16:47
Close to figuring it out. `pyvista.plot` has `show_axes=True` by default, and the following also causes the segfault:

```py
(dev) ➜  pyvista git:(master) python
Python 3.7.3 | packaged by conda-forge | (default, Dec  6 2019, 08:36:57)
[Clang 9.0.0 (tags/RELEASE_900/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyvista as pv
>>> p = pv.Plotter()
>>> p.show_axes()
>>> p.show()
[(0.20114701927183468, 1.6574758337853661, 0.4607751480446458),
 (0.0, 0.0, 0.0),
 (-0.34993648461001686, -0.21124599038556596, 0.9126442835435967)]
>>> exit()
[1]    13636 segmentation fault  python
(dev) ➜  pyvista git:(master)
```

This means the changes in #536 are likely the culprit.

**Closed** 2020-02-03 04:38 UTC
Labels: bug, priority-high
