### ISSUE TITLE
Native OpenFOAM data support

### ISSUE THREAD

**Issue by fbob** [pyvista/pyvista#924] opened 2020-10-03 08:16 UTC
OpenFOAM is unmissable in the CFD landscape and is now widely recognized as the open source CFD standard, a direct support of its data format could greatly enhance the attractiveness of pyvista.

I know that there exist a conversion tool from foam to VTK (foamToVTK) but who really enjoy using those kinds of utilities, conversion is just a pain in the ass for large meshes.

What do you think  and what's the best strategy to implement it (I already made a similar post on the meshio repository for polymesh support) ?

Thanks :)

**Comment by banesullivan** [comment] 2020-10-04 16:23
Most of the PyVista developers are not in the CFD community. Can you please share resources and links to help us understand the task? 

Can you:
- provide links to documentation/descriptions of the file formats you'd like to see support for?
- link those issues in meshio here?
- link some example (open access) datasets for us to test against?
- describe the issue with `foamToVTK`? is it merely a file conversion tool and thus a bit clunky if hoping yo load an OpenFOAM mesh in python?

------

Though I am not familiar with the CFD landscape (at all), my impression is that VTK and ParaView are widely used there... I suspect VTK already has file readers for OpenFOAM that we could easily enable. e.g. [`vtkOpenFOAMReader`](https://vtk.org/doc/nightly/html/classvtkOpenFOAMReader.html) might be relevant

**Comment by fbob** [comment] 2020-10-05 07:50
@banesullivan Many thanks for your very very relevant answer :+1: 

- OpenFOAM files structure is described here: https://cfd.direct/openfoam/user-guide/v8-case-file-structure/#x16-1220004.1
- OpenFOAM input/output file format is described here: https://cfd.direct/openfoam/user-guide/v8-basic-file-format/#x17-1230004.2
- OpenFOAM mesh  format (polyMesh) is described here : https://cfd.direct/openfoam/user-guide/v8-mesh-description/#x24-1680005.1
- meshio issue is here: https://github.com/nschloe/meshio/issues/660#issue-560040662
- here is an example of data obtained from OpenFOAM simulation : https://github.com/fbob/OpenFOAM_Case_Example.git
- the `foamToVTK` is not really an issue but the conversion process duplicates the data which area already huge (CFD is very time and memory consuming)  and takes times to do that. A direct support will greatly simplfy and speedup the workflow and your disk space will be happy.

Yes you are right VTK and Paraview are one of the standard format and post-processing app in CFD. You make me discover the `vtkOpenFOAMReader` class. I don't understand yet if a direct OpenFOAM data import is possible with it. 

Many thanks for your very helpful and relevant answer and congrats for pyvista it rocks  !

**Comment by Keou0007** [comment] 2020-10-16 09:49
I was pretty easily able to get an OpenFOAM case into a pyvista MultiBlockDataSet object, so adding an openfoam reader to pyvista would be pretty trivial. 

Depending on what you're trying to do though, the multiblockdataset may not have enough functionality to be useful. I was trying to extract various patches from my mesh which show up in paraview as Mesh Regions, but the pyvista multiblock object only contained a single block being the "internalMesh" so I couldn't find a way to access the patch data.

```
reader = vtk.vtkOpenFOAMReader()
reader.SetFileName("path/to/foamfile.foam")
reader.Update()
multi_block = pyvista.wrap(reader.GetData())
```

Ideally I would like to replace paraview with pyvista in my python workflow because importing paraview.simple is super unreliable and having to use pvpython as a seperate executable is a pain. But paraview has a lot of CFD specific functionality that pyvista isn't really trying to reproduce.

**Comment by Keou0007** [comment] 2020-10-16 12:03
As usual, I spoke too soon. And as always with anything VTK, some dogged persistence with poorly documented code pays off.

Looks like the vtkOpenFOAMReader object has all the patches except "internalMesh" turned off by default, I presume because they will usually just be boundaries and not reading them in saves time and memory. The key find for me was `reader.UpdateInformation()` to populate the reader with all the Patch names before having to read in the whole mesh.

So back to the issue at hand, adding the vtkOpenFoamReader so pyvista.load("foamfile.foam") returns a multiblock object is absolutely trivial, but a broader question remains of how to handle the features of said reader, which includes among other things the ability to read in only specific blocks of the whole data set. There is also the issue of how to handle timesteps and transient data.

I'm not familiar enough with how pyvista in general handles issues like this, but if someone wanted to point me to a good example I could template from I'd be happy to throw together a PR.

**Comment by fbob** [comment] 2020-10-16 12:45
@Keou0007 
Huge step forward with your feedback, many many thanks for this it's very useful :+1:
I'm in the same wagon: would like to replace paraview.simple with pyvista
For the lack of CFD specific features: I can't estimate how difficult a bridge between the two could be feasible or if implementing specific CFD features is an hard task.
Anyway many thanks for your very helpful and instructive feedback !

**Comment by Keou0007** [comment] 2020-10-16 13:45
Happy to help 😄 

In case it's useful, here's the code I got working for extracting objects from the mesh and writing them out as poly files. Note that I update the reader information first, then disable all the arrays before looping over the patches and enabling only the objects. This makes it run a lot faster and saves a lot of memory because my mesh is quite big. If you wanted to read in a decomposed case you'd need to use the `vtk.vtkPOpenFOAMReader` instead.

```
reader = vtk.vtkOpenFOAMReader()
reader.SetFileName("foamfile.foam")
reader.UpdateInformation()
reader.DisableAllCellArrays()
reader.DisableAllPointArrays()
reader.DisableAllPatchArrays()
reader.DisableAllLagrangianArrays()
for i in range(reader.GetNumberOfPatchArrays()):
    patch = reader.GetPatchArrayName(i)
    if re.match(r".*object.*", patch):
        reader.SetPatchArrayStatus(patch, 1)
reader.Update()
blocks = pyvista.wrap(reader.GetOutput())
patches = blocks["Patches"]
for o in patches.keys():
    polydata = patches[o]
    polydata.save(o + ".ply")
```

**Comment by MatthewFlamm** [comment] 2020-10-21 21:19
I would also love to have better support for CFD data (not just OpenFOAM).  

Right now, vector valued data cannot be accessed by component, which is a common output of CFD analysis.  There is a stale PR https://github.com/pyvista/pyvista/pull/598 to add this functionality, but it is a bit clunky in operation as it appends a new scalar to the dataset.

There is a transient data request in https://github.com/pyvista/pyvista/issues/412 as well.

**Comment by banesullivan** [comment] 2020-10-30 05:10
@Keou0007, thanks for the investigative work on figuring out how to use `vtkOpenFOAMReader`! You're right that adding the reader could be trivial though it comes with a lot of options and adding support for those options isn't so trivial.

This is very similar to the "support" we added for Exodus files and ended up just making a dedicated function for that format that advanced users can call and have all the arguments set to some preferable default (e.g. loading all patches in this case) which `pyvista.read()` will utilize by default if a `.foam` file is passed.

I'd support a PR to add a new `read_foam` function in `pyvista/utilities/fileio.py` that has a whole lot of keyword arguments to control the `vtkOpenFOAMReader` then just add the appropriate `elif ext in ['.foam']` statement in `read()` and have it point to that function.

-----

Another route would be to utilize the `attrs` argument of `read()` if adding `vtkOpenFOAMReader` to `READERS` though this isn't too user friendly. This is a super old feature I added a long while back to be able to quickly adjust the parameters of any reader.

**Comment by Keou0007** [comment] 2020-10-30 05:28
Turns out the `read()` function already recognises `.foam` extensions and points it to `vtkOpenFOAMReader` and the attrs argument does allow using some of the options as you suggest, so that's actually already implemented. Unfortuantely most OpenFOAM data is decomposed from processing in parallel, so pointing to the serial data reader is not necessarily what you want.

I had considered starting to pull together a draft PR with some ideas as you suggest. One idea, as you say, is to create a `read_foam()` function that wraps the reader (either serial or parallel) and provides options to easily access its capabilities. Another idea I had was to subclass the multiblock object to an OpenFOAMData object and add a bunch of options for dealing with decomposed data and time series as well.

Unfortunately, when I started playing around with vtkPOpenFOAMReader, I wasn't able to get it to read any decomposed data or recognise a time series in the way it seems like it should be able to. So for now that's all gone in the too hard basket. Maybe when I'm less busy and feeling REALLY motivated...

**Comment by MattAtSteady** [comment] 2021-03-17 17:08
@Keou0007 have you had any luck with `vtkPOpenFOAMReader`? I've tried the following:

`    reader = vtk.vtkPOpenFOAMReader()`
`    reader.SetFileName(dir_path+"/foamfile.foam")`
`    reader.SetCaseType(0)    # 0 - decomposed, 1 - reconstructed (default value)`
`    reader.Update()`

vtk crashes when I call `reader.Update()` with `Segmentation fault: 11`. I've tried different reader settings, it seems that `SetCaseType(0)` is causing the `Update()` crash

**Comment by Keou0007** [comment] 2021-03-18 09:04
Nope, I pretty much gave up trying to get the OpenFOAM reader to work. 

I use function objects to do sampling during the run and output vtk objects which are easy to import into pyvista. The only thing I was using reader for was to extract the geometry from the mesh so I can add it into visualisations.
I was able to get it to read the polyMesh for that purpose, but as soon as I tried to read a decomposed case or any time directories I could never get it to work. 

Sorry!

**Comment by MattAtSteady** [comment] 2021-03-18 14:26
With the serial reader I'm able to handle time by accessing the time values and setting the time with the vtk reader before wrapping the data to PyVista. This means you have to handle time with the vtk reader before passing to PyVista. Here's an example.
```
reader = vtk.vtkOpenFOAMReader()
reader.SetFileName(dir_path+"/foamfile.foam")
reader.UpdateInformation()
time_array = reader.GetTimeValues()
reader.SetTimeValue(time_array.GetRange()[1])  # Set read time to latest time step
reader.Update()
multi_block = pyvista.wrap(reader.GetOutput())
```

I've emailed the creator of the [vtkPOpenFOAMReader](https://vtk.org/doc/nightly/html/classvtkPOpenFOAMReader.html#details) class. Hopefully he will respond and I can report back.

**Comment by akaszynski** [comment] 2021-03-18 17:30
One day, hopefully soon, we can add in a fully featured openfoam reader that wraps the parallel (or serial) reader.  If possible, would anyone on this thread be able to submit a PR for this?  If not, posting code and (small) example files would be sufficient for me to prototype something.

**Comment by Keou0007** [comment] 2021-03-19 00:37
I'd be happy to contribute to the python/pyvista side of this, but I wasn't able to get the parallel reader working how I'd expect at all. Given most OpenFOAM data is decomposed from running in parallel and its a non-trivial extra step to reconstruct results, never mind a lot slower to read, without a suitable reader this is a fools errand imho.

**Comment by ewsconsulting** [comment] 2021-04-06 12:38
> With the serial reader I'm able to handle time by accessing the time values and setting the time with the vtk reader before wrapping the data to PyVista. This means you have to handle time with the vtk reader before passing to PyVista. Here's an example.
> 
> ```
> reader = vtk.vtkOpenFOAMReader()
> reader.SetFileName(dir_path+"/foamfile.foam")
> reader.UpdateInformation()
> time_array = reader.GetTimeValues()
> reader.SetTimeValue(time_array.GetRange()[1])  # Set read time to latest time step
> reader.Update()
> multi_block = pyvista.wrap(reader.GetOutput())
> ```
> 
> I've emailed the creator of the [vtkPOpenFOAMReader](https://vtk.org/doc/nightly/html/classvtkPOpenFOAMReader.html#details) class. Hopefully he will respond and I can report back.

Hi!
I suggest you read this thread for changing the time values.
https://vtk.org/pipermail/vtkusers/2016-November/097113.html

I personally use this:

```python
reader.UpdateInformation()
timesteps = vtk_to_numpy(reader.GetTimeValues())
print(timesteps)
outinfo = reader.GetExecutive().GetOutputInformation(0)
infkey = vtk.vtkStreamingDemandDrivenPipeline.UPDATE_TIME_STEP()
outinfo.Set(infkey, timesteps[-1])
reader.Update()
```

**Comment by MatthewFlamm** [comment] 2021-12-17 18:48
With the newer versions of pyvista.  It is now possible to do something like this:

```py
reader = pyvista.get_reader("path_to_case_folder/case.foam")
reader.set_active_time_value(reader.time_values[-1])  # use last time point
mesh = reader.read()
```

This issue seems to be mainly about time handling, which is now implemented.  Can this be closed?

**Comment by Keou0007** [comment] 2021-12-20 05:23
I've had a little play around with this and my opinion is that the OpenFOAM reader is still WIP, which I would assume means this issue is not ready to be closed.

While it is possible to create an OpenFOAM reader object and set the time specifically now, which is an important step, the default reader still does not support decomposed cases. The vtkPOpenFOAMReader in theory supports this, and so probably should be the default reader that pyvista uses instead of the standard reader. But as I mentioned above, I've not had any luck getting that reader to read a decomposed case and the documentation is not super helpful.
It _is_ possible, since Paraview reads decomposed cases just fine and Paraview uses the same readers from the vtk library afaik. Perhaps someone working at Kitware can go and ask the Paraview team how reading OF cases in parallel works?

As an aside, while I was playing around with the pyvista openfoam reader object just now, I ran into this exception.
```
reader.active_time_value

---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
/var/folders/_w/4zzbmb5d2fs31j1hlm133xrr0000gn/T/ipykernel_44495/1987994017.py in <module>
----> 1 reader.active_time_value

~/opt/miniconda3/lib/python3.8/site-packages/pyvista/utilities/reader.py in active_time_value(self)
    614     @property
    615     def active_time_value(self):  # noqa: D102
--> 616         raise NotImplementedError("vtkOpenFOAMReader does not yet support this")
    617 
    618     def set_active_time_value(self, time_value):  # noqa: D102

NotImplementedError: vtkOpenFOAMReader does not yet support this
```

the vtkOpenFOAMReader class _does_ support this, as evidenced by `reader.reader.GetTimeValue()` working just fine, so this really should be corrected. It's low-hanging fruit if there's an intern or something floating around. I'd be happy to do a PR myself, but I wouldn't be willing to commit any time to it until after new year now.

**Comment by akaszynski** [comment] 2021-12-20 05:46
> I'd be happy to do a PR myself, but I wouldn't be willing to commit any time to it until after new year now.

I'd really appreciate that, and I'm ready to review it when the times comes for you to submit it.

**Comment by MatthewFlamm** [comment] 2021-12-22 02:29
#1896 now also adds in support for `GetTimeValue` for `vtk>=9.1.0`

**Comment by piyueh** [comment] 2022-04-04 07:59
Not sure if this is the right place to ask questions. How to make the OpenFOAM data reader use double-precision floats? Thanks!

**Comment by MatthewFlamm** [comment] 2022-04-04 11:25
I don't have a dataset to test against.  You can try this with something like:

```py
reader = pyvista.OpenFOAMReader('case.foam')
reader.reader.Use64BitFloatsOn()
reader.reader.Use64BitLabelsOn()  # another option
```

We should expose this in the pyvista interface.

**Comment by MatthewFlamm** [comment] 2022-04-04 14:44
It seems that the default is already to use `Use64BitFloatsOn()`, there is a cryptic statement in the [vtk documentation](https://vtk.org/doc/nightly/html/classvtkOpenFOAMReader.html#ae9f70c105bf95ddf3bf03182fbdf1bae) about this:

> Note that vtkFloatArrays may still be used in the output if this is true. This flag is only used to ensure that binary data is correctly parsed.

**Comment by piyueh** [comment] 2022-04-06 17:19
> It seems that the default is already to use `Use64BitFloatsOn()`, there is a cryptic statement in the [vtk documentation](https://vtk.org/doc/nightly/html/classvtkOpenFOAMReader.html#ae9f70c105bf95ddf3bf03182fbdf1bae) about this:
> 
> > Note that vtkFloatArrays may still be used in the output if this is true. This flag is only used to ensure that binary data is correctly parsed.

Oops, I think I finally correctly understood this statement. It basically means the flag is used to ensure `vtkOpenFOAMReader` knows the data in files are `double`s when parsing, but the reader still casts and stores the data with `float` (i.e., the use of `vtkFloatArrays`.)

This use of `vtkFloatArrays` is hard-coded in VTK's `vtkOpenFOAMReader` implementation. So I guess there's nothing PyVista can do to mitigate the issue unless we write our own OpenFOAM reader.

**Comment by umutkaya-ugent** [comment] 2022-04-20 11:31
This restriction doesn't make sense. Can anyone suggest a workaround to the double precision problem?

@piyueh can you point to the hard-coded part in `vtkOpenFOAMReader` ?

**Comment by MatthewFlamm** [comment] 2022-04-20 14:57
I think this is a `vtk` question.  I don't think there is anything PyVista can do.

There are many uses of `vtkFloatArray` in `vtkOpenFOAMReader`.  See https://github.com/Kitware/VTK/blob/master/IO/Geometry/vtkOpenFOAMReader.cxx.

**Comment by piyueh** [comment] 2022-04-20 16:44
> This restriction doesn't make sense. Can anyone suggest a workaround to the double precision problem?

I agree there's probably nothing PyVista can do. I myself implement my own OpenFOAM reader and construct `pyvista.UnstructuredMesh` objects manually. However, I then realized my reader may only work with my simple OpenFOAM use cases (icoFOAM + blockMesh + very simple geometry). It doesn't work with more complicated use cases and mesh. 

> @piyueh can you point to the hard-coded part in `vtkOpenFOAMReader` ?

All arrays holding floating numbers in the file pointed by @MatthewFlamm are `vtkFloatArray`, which only holds 32bit floating numbers.

**Comment by MatthewFlamm** [comment] 2022-08-02 16:08
Now that POpenFOAMReader is implemented, I think that the core functionality for reading OpenFOAM data is now complete.  There are more features for OpenFOAM reading that can be implemented, e.g. 64 bit data/labels, but I think these are best tracked on separate issues, or a single issue with a concrete list of features to add.

I'm going to close this, but if anyone feels differently, we can reopen.

**Closed by MatthewFlamm** 2022-08-02 16:08 UTC
Labels: feature-request, file-formats
