### ISSUE TITLE
enable_cell_picking is not picking the cell clicked

### ISSUE THREAD

**Issue by rodrigomologni** [pyvista/pyvista#3550] opened 2022-11-04 13:53 UTC
### Describe the bug, what's wrong, and what you expected.

Hi Team!

I don't know why when I use `show_cells` `enable_cell_picking` is not picking the cell clicked.

Download: [BRUGGE60K_FY-SF-KM-1-1.zip](https://github.com/pyvista/pyvista/files/9938706/BRUGGE60K_FY-SF-KM-1-1.zip)

### Steps to reproduce the bug.

```python
import pyvista as pv

def pick_cell(cell):
    ...

grid = pv.ExplicitStructuredGrid("BRUGGE60K_FY-SF-KM-1-1.vtu")

plotter = pv.Plotter()
plotter.add_axes()
plotter.add_mesh(grid, show_edges=True, color="white")
plotter.enable_cell_picking(callback=pick_cell, through=False)
plotter.show()
```
![image](https://user-images.githubusercontent.com/1608652/199984485-c44da5a3-681b-4920-9a05-d0085f8abe46.png)

```python
import pyvista as pv

def pick_cell(cell):
    ...

grid = pv.ExplicitStructuredGrid("BRUGGE60K_FY-SF-KM-1-1.vtu")
grid.show_cells(inplace=True)  # new line

plotter = pv.Plotter()
plotter.add_axes()
plotter.add_mesh(grid, show_edges=True, color="white")
plotter.enable_cell_picking(callback=pick_cell, through=False)
plotter.show()
```
![image](https://user-images.githubusercontent.com/1608652/199984424-687733a5-1fb8-4537-a51f-3f967e545abc.png)

### System Information

```shell
--------------------------------------------------------------------------------
  Date: Fri Nov 04 10:22:11 2022 Hora oficial do Brasil

                OS : Windows
            CPU(s) : 8
           Machine : AMD64
      Architecture : 64bit
       Environment : Python
        GPU Vendor : ATI Technologies Inc.
      GPU Renderer : AMD Radeon (TM) R9 370
       GPU Version : 4.5.13571 Core Profile Context 19.30.02 26.20.13002.133

  Python 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64
  bit (AMD64)]

           pyvista : 0.36.1
               vtk : 9.2.2
             numpy : 1.23.4
           imageio : 2.22.3
           appdirs : 1.4.4
            scooby : 0.7.0
        matplotlib : 3.6.2
             scipy : 1.9.3
              tqdm : 4.64.1
--------------------------------------------------------------------------------
```

**Comment by banesullivan** [comment] 2022-11-04 16:23
Are you only seeing this with explicit structured grids?

**Comment by rodrigomologni** [comment] 2022-11-04 16:41
Hi @banesullivan! Yes. The problem gets worse if I use `cast_to_unstructured_grid`. I don't know if the problem is in the dataset or in the PyVista, sorry. I tested with other explicit structured grids. Same problem.

**Comment by rodrigomologni** [comment] 2022-11-04 17:11
@banesullivan I think the problem is in the dataset. I am investigating... Sorry!

**Comment by rodrigomologni** [comment] 2022-11-04 17:56
@banesullivan I couldn't identify where the problem is. I think it's in the grid construction, but I'm not sure about that. You can close this issue if you wish. Sorry!

**Comment by banesullivan** [comment] 2022-11-04 18:02
I still want to investigate this a bit, so I'm going to leave this open.

Also. I recently made some changes to cell picking that just landed. Could you verify the issue is still happening on the latest pyvista?

**Comment by rodrigomologni** [comment] 2022-11-05 10:53
Yes, I used PyVista v0.34.2 up to the latest.

**Comment by rodrigomologni** [comment] 2022-11-05 11:53
@banesullivan cell picking on explicit structured grids is working in VTK.

```python
from vtkmodules.vtkCommonCore import vtkIdList
from vtkmodules.vtkFiltersCore import vtkUnstructuredGridToExplicitStructuredGrid
from vtkmodules.vtkIOXML import vtkXMLUnstructuredGridReader
from vtkmodules.vtkInteractionStyle import vtkInteractorStyleRubberBandPick
from vtkmodules.vtkRenderingCore import (
    vtkActor,
    vtkDataSetMapper,
    vtkRenderWindow,
    vtkRenderWindowInteractor,
    vtkRenderer,
    vtkCellPicker
)
from vtkmodules.vtkFiltersExtraction import vtkExtractCells
from vtkmodules.vtkInteractionStyle import vtkInteractorStyleSwitch  # noqa
from vtkmodules import vtkRenderingOpenGL2  # noqa


grid_reader = vtkXMLUnstructuredGridReader()
grid_reader.SetFileName("BRUGGE60K_FY-SF-KM-1-1.vtu")
grid_reader.Update()

grid_converter = vtkUnstructuredGridToExplicitStructuredGrid()
grid_converter.GlobalWarningDisplayOff()  # hide VTK errors
grid_converter.SetInputConnection(grid_reader.GetOutputPort())
grid_converter.SetInputArrayToProcess(0, 0, 0, 1, "BLOCK_I")
grid_converter.SetInputArrayToProcess(1, 0, 0, 1, "BLOCK_J")
grid_converter.SetInputArrayToProcess(2, 0, 0, 1, "BLOCK_K")
grid_converter.Update()

grid = grid_converter.GetOutput()
grid.GetCellData().RemoveArray("vtkGhostType")  # show hide cells

grid_mapper = vtkDataSetMapper()
grid_mapper.SetInputData(grid)
grid_mapper.ScalarVisibilityOff()

grid_actor = vtkActor()
grid_actor.SetMapper(grid_mapper)
grid_actor.GetProperty().EdgeVisibilityOn()
grid_actor.GetProperty().SetColor(1, 1, 1)

renderer = vtkRenderer()
renderer.AddActor(grid_actor)
renderer.SetBackground(.3, .3, .3)

window = vtkRenderWindow()
window.AddRenderer(renderer)
window.SetSize(1024, 768)

picker = vtkCellPicker()

last_cell_actor = None

def right_button_pressed(caller, event):
    x, y = interactor.GetEventPosition()
    picker.Pick(x, y, 0, renderer)

    cell_id = picker.GetCellId()
    print(cell_id)

    cell_ids = vtkIdList()
    cell_ids.InsertNextId(cell_id)

    cell_extractor = vtkExtractCells()
    cell_extractor.SetInputData(grid)
    cell_extractor.SetCellList(cell_ids)
    cell_extractor.Update()

    cell = cell_extractor.GetOutput()

    cell_mapper = vtkDataSetMapper()
    cell_mapper.SetInputData(cell)

    cell_actor = vtkActor()
    cell_actor.SetMapper(cell_mapper)
    cell_actor.GetProperty().SetRepresentationToWireframe()
    cell_actor.GetProperty().SetColor(1, 0, 0)
    cell_actor.GetProperty().SetLineWidth(3)

    global last_cell_actor

    if last_cell_actor:
        renderer.RemoveActor(last_cell_actor)

    renderer.AddActor(cell_actor)

    last_cell_actor = cell_actor

interactor = vtkRenderWindowInteractor()
interactor.SetRenderWindow(window)
interactor.GetInteractorStyle().SetCurrentStyleToTrackballCamera()
interactor.AddObserver("RightButtonPressEvent", right_button_pressed)
interactor.Start()
```

**Closed** 2023-04-10 18:15 UTC
Labels: bug
