### ISSUE TITLE
Warning: Unable to enable faulthandle

### ISSUE THREAD

**Issue by giovform** [pyvista/pyvista#1193] opened 2021-02-19 21:16 UTC
I am getting this message at my python console startup, after installing pyvista.

```
C:\Users\giovanni\AppData\Local\NA-MIC\Slicer-4.11.20200930-2021-02-11-win-amd64\lib\Python\Lib\site-packages\pyvista\__init__.py:21: UserWarning: Unable to enable faulthandler:
'PythonQtStdOutRedirect' object has no attribute 'fileno'
  warnings.warn(f'Unable to enable faulthandler:\n{e}')
```

**System Information:**
```txt
--------------------------------------------------------------------------------
  Date: Fri Feb 19 18:14:02 2021 Hora oficial do Brasil

                OS : Windows
            CPU(s) : 16
           Machine : AMD64
      Architecture : 64bit
               RAM : 31.9 GB
       Environment : Python
        GPU Vendor : NVIDIA Corporation
      GPU Renderer : GeForce GTX 1660/PCIe/SSE2
       GPU Version : 4.5.0 NVIDIA 456.71

  Python 3.6.7 (default, Feb 12 2021, 09:24:38) [MSC v.1923 64 bit (AMD64)]

           pyvista : 0.28.1
               vtk : 8.2.0
             numpy : 1.19.1
           imageio : 2.9.0
           appdirs : 1.4.4
            scooby : 0.5.6
            meshio : 4.3.9
        matplotlib : 3.2.1
             scipy : 1.4.1
              tqdm : 4.50.2
--------------------------------------------------------------------------------
```

**Comment by banesullivan** [comment] 2021-02-19 21:48
Possible duplicate of #1186 ?

**Comment by akaszynski** [comment] 2021-02-20 17:49
We've disabled the faulthandler and this will be out on the next major release (at the end of this month).  See #1187

**Closed by akaszynski** 2021-02-20 17:49 UTC
