### ISSUE TITLE
exit button causes crash

### ISSUE THREAD

**Issue by mmagnuski** [pyvista/pyvista#186] opened 2019-04-21 18:45 UTC
**EDIT:** *this is a duplicate of #135*

I've run the example you suggested in my previous issue:

```python
from vtki import examples
mesh = examples.download_st_helens()
warped = mesh.warp_by_scalar()
warped.plot(notebook=False)
```
It worked very well but when I closed the window and returned control to the jupyter lab I got the following stream of `list index out of range` errors:

<details>

```python-traceback
ERROR:root:#version 120
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in __call__(self, obj, event, message)
     47         self.__event_occurred = True
     48         self.__message_etc = message
---> 49         kind, path, address, alert = self.parse_message(message)
     50         self.__message = alert
     51         if self.__log:

~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in parse_message(message)
     32         # Message format
     33         regex = re.compile(r'([A-Z]+):\sIn\s(.+),\sline\s.+\n\w+\s(.+):\s(.+)')
---> 34         kind, path, address, alert = regex.findall(message)[0]
     35         return kind, path, address, alert
     36 

IndexError: list index out of range
ERROR:root:Shader object was not initialized, cannot attach it.
ERROR:root:#version 120
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in __call__(self, obj, event, message)
     47         self.__event_occurred = True
     48         self.__message_etc = message
---> 49         kind, path, address, alert = self.parse_message(message)
     50         self.__message = alert
     51         if self.__log:

~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in parse_message(message)
     32         # Message format
     33         regex = re.compile(r'([A-Z]+):\sIn\s(.+),\sline\s.+\n\w+\s(.+):\s(.+)')
---> 34         kind, path, address, alert = regex.findall(message)[0]
     35         return kind, path, address, alert
     36 

IndexError: list index out of range
ERROR:root:#version 120
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in __call__(self, obj, event, message)
     47         self.__event_occurred = True
     48         self.__message_etc = message
---> 49         kind, path, address, alert = self.parse_message(message)
     50         self.__message = alert
     51         if self.__log:

~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in parse_message(message)
     32         # Message format
     33         regex = re.compile(r'([A-Z]+):\sIn\s(.+),\sline\s.+\n\w+\s(.+):\s(.+)')
---> 34         kind, path, address, alert = regex.findall(message)[0]
     35         return kind, path, address, alert
     36 

IndexError: list index out of range
ERROR:root:#version 120
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in __call__(self, obj, event, message)
     47         self.__event_occurred = True
     48         self.__message_etc = message
---> 49         kind, path, address, alert = self.parse_message(message)
     50         self.__message = alert
     51         if self.__log:

~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in parse_message(message)
     32         # Message format
     33         regex = re.compile(r'([A-Z]+):\sIn\s(.+),\sline\s.+\n\w+\s(.+):\s(.+)')
---> 34         kind, path, address, alert = regex.findall(message)[0]
     35         return kind, path, address, alert
     36 

IndexError: list index out of range
ERROR:root:#version 120
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in __call__(self, obj, event, message)
     47         self.__event_occurred = True
     48         self.__message_etc = message
---> 49         kind, path, address, alert = self.parse_message(message)
     50         self.__message = alert
     51         if self.__log:

~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in parse_message(message)
     32         # Message format
     33         regex = re.compile(r'([A-Z]+):\sIn\s(.+),\sline\s.+\n\w+\s(.+):\s(.+)')
---> 34         kind, path, address, alert = regex.findall(message)[0]
     35         return kind, path, address, alert
     36 

IndexError: list index out of range
ERROR:root:#version 120
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in __call__(self, obj, event, message)
     47         self.__event_occurred = True
     48         self.__message_etc = message
---> 49         kind, path, address, alert = self.parse_message(message)
     50         self.__message = alert
     51         if self.__log:

~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in parse_message(message)
     32         # Message format
     33         regex = re.compile(r'([A-Z]+):\sIn\s(.+),\sline\s.+\n\w+\s(.+):\s(.+)')
---> 34         kind, path, address, alert = regex.findall(message)[0]
     35         return kind, path, address, alert
     36 

IndexError: list index out of range
ERROR:root:#version 120
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in __call__(self, obj, event, message)
     47         self.__event_occurred = True
     48         self.__message_etc = message
---> 49         kind, path, address, alert = self.parse_message(message)
     50         self.__message = alert
     51         if self.__log:

~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in parse_message(message)
     32         # Message format
     33         regex = re.compile(r'([A-Z]+):\sIn\s(.+),\sline\s.+\n\w+\s(.+):\s(.+)')
---> 34         kind, path, address, alert = regex.findall(message)[0]
     35         return kind, path, address, alert
     36 

IndexError: list index out of range
ERROR:root:Shader object was not initialized, cannot attach it.
ERROR:root:#version 120
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in __call__(self, obj, event, message)
     47         self.__event_occurred = True
     48         self.__message_etc = message
---> 49         kind, path, address, alert = self.parse_message(message)
     50         self.__message = alert
     51         if self.__log:

~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in parse_message(message)
     32         # Message format
     33         regex = re.compile(r'([A-Z]+):\sIn\s(.+),\sline\s.+\n\w+\s(.+):\s(.+)')
---> 34         kind, path, address, alert = regex.findall(message)[0]
     35         return kind, path, address, alert
     36 

IndexError: list index out of range
ERROR:root:#version 120
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in __call__(self, obj, event, message)
     47         self.__event_occurred = True
     48         self.__message_etc = message
---> 49         kind, path, address, alert = self.parse_message(message)
     50         self.__message = alert
     51         if self.__log:

~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in parse_message(message)
     32         # Message format
     33         regex = re.compile(r'([A-Z]+):\sIn\s(.+),\sline\s.+\n\w+\s(.+):\s(.+)')
---> 34         kind, path, address, alert = regex.findall(message)[0]
     35         return kind, path, address, alert
     36 

IndexError: list index out of range
ERROR:root:Shader object was not initialized, cannot attach it.
ERROR:root:#version 120
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in __call__(self, obj, event, message)
     47         self.__event_occurred = True
     48         self.__message_etc = message
---> 49         kind, path, address, alert = self.parse_message(message)
     50         self.__message = alert
     51         if self.__log:

~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in parse_message(message)
     32         # Message format
     33         regex = re.compile(r'([A-Z]+):\sIn\s(.+),\sline\s.+\n\w+\s(.+):\s(.+)')
---> 34         kind, path, address, alert = regex.findall(message)[0]
     35         return kind, path, address, alert
     36 

IndexError: list index out of range
ERROR:root:#version 120
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in __call__(self, obj, event, message)
     47         self.__event_occurred = True
     48         self.__message_etc = message
---> 49         kind, path, address, alert = self.parse_message(message)
     50         self.__message = alert
     51         if self.__log:

~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in parse_message(message)
     32         # Message format
     33         regex = re.compile(r'([A-Z]+):\sIn\s(.+),\sline\s.+\n\w+\s(.+):\s(.+)')
---> 34         kind, path, address, alert = regex.findall(message)[0]
     35         return kind, path, address, alert
     36 

IndexError: list index out of range
ERROR:root:#version 120
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in __call__(self, obj, event, message)
     47         self.__event_occurred = True
     48         self.__message_etc = message
---> 49         kind, path, address, alert = self.parse_message(message)
     50         self.__message = alert
     51         if self.__log:

~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in parse_message(message)
     32         # Message format
     33         regex = re.compile(r'([A-Z]+):\sIn\s(.+),\sline\s.+\n\w+\s(.+):\s(.+)')
---> 34         kind, path, address, alert = regex.findall(message)[0]
     35         return kind, path, address, alert
     36 

IndexError: list index out of range
ERROR:root:#version 120
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in __call__(self, obj, event, message)
     47         self.__event_occurred = True
     48         self.__message_etc = message
---> 49         kind, path, address, alert = self.parse_message(message)
     50         self.__message = alert
     51         if self.__log:

~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in parse_message(message)
     32         # Message format
     33         regex = re.compile(r'([A-Z]+):\sIn\s(.+),\sline\s.+\n\w+\s(.+):\s(.+)')
---> 34         kind, path, address, alert = regex.findall(message)[0]
     35         return kind, path, address, alert
     36 

IndexError: list index out of range
ERROR:root:Shader object was not initialized, cannot attach it.
ERROR:root:#version 120
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in __call__(self, obj, event, message)
     47         self.__event_occurred = True
     48         self.__message_etc = message
---> 49         kind, path, address, alert = self.parse_message(message)
     50         self.__message = alert
     51         if self.__log:

~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in parse_message(message)
     32         # Message format
     33         regex = re.compile(r'([A-Z]+):\sIn\s(.+),\sline\s.+\n\w+\s(.+):\s(.+)')
---> 34         kind, path, address, alert = regex.findall(message)[0]
     35         return kind, path, address, alert
     36 

IndexError: list index out of range
ERROR:root:#version 120
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in __call__(self, obj, event, message)
     47         self.__event_occurred = True
     48         self.__message_etc = message
---> 49         kind, path, address, alert = self.parse_message(message)
     50         self.__message = alert
     51         if self.__log:

~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in parse_message(message)
     32         # Message format
     33         regex = re.compile(r'([A-Z]+):\sIn\s(.+),\sline\s.+\n\w+\s(.+):\s(.+)')
---> 34         kind, path, address, alert = regex.findall(message)[0]
     35         return kind, path, address, alert
     36 

IndexError: list index out of range
ERROR:root:#version 120
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in __call__(self, obj, event, message)
     47         self.__event_occurred = True
     48         self.__message_etc = message
---> 49         kind, path, address, alert = self.parse_message(message)
     50         self.__message = alert
     51         if self.__log:

~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in parse_message(message)
     32         # Message format
     33         regex = re.compile(r'([A-Z]+):\sIn\s(.+),\sline\s.+\n\w+\s(.+):\s(.+)')
---> 34         kind, path, address, alert = regex.findall(message)[0]
     35         return kind, path, address, alert
     36 

IndexError: list index out of range
ERROR:root:#version 120
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in __call__(self, obj, event, message)
     47         self.__event_occurred = True
     48         self.__message_etc = message
---> 49         kind, path, address, alert = self.parse_message(message)
     50         self.__message = alert
     51         if self.__log:

~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in parse_message(message)
     32         # Message format
     33         regex = re.compile(r'([A-Z]+):\sIn\s(.+),\sline\s.+\n\w+\s(.+):\s(.+)')
---> 34         kind, path, address, alert = regex.findall(message)[0]
     35         return kind, path, address, alert
     36 

IndexError: list index out of range
ERROR:root:#version 120
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in __call__(self, obj, event, message)
     47         self.__event_occurred = True
     48         self.__message_etc = message
---> 49         kind, path, address, alert = self.parse_message(message)
     50         self.__message = alert
     51         if self.__log:

~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in parse_message(message)
     32         # Message format
     33         regex = re.compile(r'([A-Z]+):\sIn\s(.+),\sline\s.+\n\w+\s(.+):\s(.+)')
---> 34         kind, path, address, alert = regex.findall(message)[0]
     35         return kind, path, address, alert
     36 

IndexError: list index out of range
ERROR:root:#version 120
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in __call__(self, obj, event, message)
     47         self.__event_occurred = True
     48         self.__message_etc = message
---> 49         kind, path, address, alert = self.parse_message(message)
     50         self.__message = alert
     51         if self.__log:

~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in parse_message(message)
     32         # Message format
     33         regex = re.compile(r'([A-Z]+):\sIn\s(.+),\sline\s.+\n\w+\s(.+):\s(.+)')
---> 34         kind, path, address, alert = regex.findall(message)[0]
     35         return kind, path, address, alert
     36 

IndexError: list index out of range
ERROR:root:#version 120
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in __call__(self, obj, event, message)
     47         self.__event_occurred = True
     48         self.__message_etc = message
---> 49         kind, path, address, alert = self.parse_message(message)
     50         self.__message = alert
     51         if self.__log:

~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in parse_message(message)
     32         # Message format
     33         regex = re.compile(r'([A-Z]+):\sIn\s(.+),\sline\s.+\n\w+\s(.+):\s(.+)')
---> 34         kind, path, address, alert = regex.findall(message)[0]
     35         return kind, path, address, alert
     36 

IndexError: list index out of range
ERROR:root:#version 120
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in __call__(self, obj, event, message)
     47         self.__event_occurred = True
     48         self.__message_etc = message
---> 49         kind, path, address, alert = self.parse_message(message)
     50         self.__message = alert
     51         if self.__log:

~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in parse_message(message)
     32         # Message format
     33         regex = re.compile(r'([A-Z]+):\sIn\s(.+),\sline\s.+\n\w+\s(.+):\s(.+)')
---> 34         kind, path, address, alert = regex.findall(message)[0]
     35         return kind, path, address, alert
     36 

IndexError: list index out of range
ERROR:root:#version 120
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in __call__(self, obj, event, message)
     47         self.__event_occurred = True
     48         self.__message_etc = message
---> 49         kind, path, address, alert = self.parse_message(message)
     50         self.__message = alert
     51         if self.__log:

~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in parse_message(message)
     32         # Message format
     33         regex = re.compile(r'([A-Z]+):\sIn\s(.+),\sline\s.+\n\w+\s(.+):\s(.+)')
---> 34         kind, path, address, alert = regex.findall(message)[0]
     35         return kind, path, address, alert
     36 

IndexError: list index out of range
ERROR:root:#version 120
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in __call__(self, obj, event, message)
     47         self.__event_occurred = True
     48         self.__message_etc = message
---> 49         kind, path, address, alert = self.parse_message(message)
     50         self.__message = alert
     51         if self.__log:

~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in parse_message(message)
     32         # Message format
     33         regex = re.compile(r'([A-Z]+):\sIn\s(.+),\sline\s.+\n\w+\s(.+):\s(.+)')
---> 34         kind, path, address, alert = regex.findall(message)[0]
     35         return kind, path, address, alert
     36 

IndexError: list index out of range
ERROR:root:#version 120
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in __call__(self, obj, event, message)
     47         self.__event_occurred = True
     48         self.__message_etc = message
---> 49         kind, path, address, alert = self.parse_message(message)
     50         self.__message = alert
     51         if self.__log:

~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in parse_message(message)
     32         # Message format
     33         regex = re.compile(r'([A-Z]+):\sIn\s(.+),\sline\s.+\n\w+\s(.+):\s(.+)')
---> 34         kind, path, address, alert = regex.findall(message)[0]
     35         return kind, path, address, alert
     36 

IndexError: list index out of range
ERROR:root:#version 120
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in __call__(self, obj, event, message)
     47         self.__event_occurred = True
     48         self.__message_etc = message
---> 49         kind, path, address, alert = self.parse_message(message)
     50         self.__message = alert
     51         if self.__log:

~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in parse_message(message)
     32         # Message format
     33         regex = re.compile(r'([A-Z]+):\sIn\s(.+),\sline\s.+\n\w+\s(.+):\s(.+)')
---> 34         kind, path, address, alert = regex.findall(message)[0]
     35         return kind, path, address, alert
     36 

IndexError: list index out of range
ERROR:root:#version 120
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in __call__(self, obj, event, message)
     47         self.__event_occurred = True
     48         self.__message_etc = message
---> 49         kind, path, address, alert = self.parse_message(message)
     50         self.__message = alert
     51         if self.__log:

~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in parse_message(message)
     32         # Message format
     33         regex = re.compile(r'([A-Z]+):\sIn\s(.+),\sline\s.+\n\w+\s(.+):\s(.+)')
---> 34         kind, path, address, alert = regex.findall(message)[0]
     35         return kind, path, address, alert
     36 

IndexError: list index out of range
ERROR:root:#version 120
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in __call__(self, obj, event, message)
     47         self.__event_occurred = True
     48         self.__message_etc = message
---> 49         kind, path, address, alert = self.parse_message(message)
     50         self.__message = alert
     51         if self.__log:

~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in parse_message(message)
     32         # Message format
     33         regex = re.compile(r'([A-Z]+):\sIn\s(.+),\sline\s.+\n\w+\s(.+):\s(.+)')
---> 34         kind, path, address, alert = regex.findall(message)[0]
     35         return kind, path, address, alert
     36 

IndexError: list index out of range
ERROR:root:#version 120
```

</details>

**Comment by banesullivan** [comment] 2019-04-21 23:13
I think fa66ef4 should have fixed this

**Comment by banesullivan** [comment] 2019-04-21 23:15
Could you install `vtki` from the master branch and test? Just to make sure it fixed the problem before we tag a release.

```bash
pip install git+git://github.com/vtkiorg/vtki@master
```

**Comment by mmagnuski** [comment] 2019-04-22 09:43
I'll try that later today.

**Comment by mmagnuski** [comment] 2019-04-22 11:38
After pip installing from master I still get errors although they are a bit different:

```
ERROR:root:#version 120
WARNING:root:ERROR: In C:\VPP\standalone-build\VTK-source\Rendering\OpenGL2\vtkShaderProgram.cxx, line 431
vtkShaderProgram (0000020B04DF7C00): 


ERROR:root:Shader object was not initialized, cannot attach it.
ERROR:root:#version 120
WARNING:root:ERROR: In C:\VPP\standalone-build\VTK-source\Rendering\OpenGL2\vtkShaderProgram.cxx, line 431
vtkShaderProgram (0000020B04DF6460): 


ERROR:root:#version 120
WARNING:root:ERROR: In C:\VPP\standalone-build\VTK-source\Rendering\OpenGL2\vtkShaderProgram.cxx, line 431
vtkShaderProgram (0000020B04DF6460): 


ERROR:root:#version 120
WARNING:root:ERROR: In C:\VPP\standalone-build\VTK-source\Rendering\OpenGL2\vtkShaderProgram.cxx, line 431
vtkShaderProgram (0000020B04DF6460): 


ERROR:root:#version 120
WARNING:root:ERROR: In C:\VPP\standalone-build\VTK-source\Rendering\OpenGL2\vtkShaderProgram.cxx, line 431
vtkShaderProgram (0000020B04DF6460): 


ERROR:root:#version 120
WARNING:root:ERROR: In C:\VPP\standalone-build\VTK-source\Rendering\OpenGL2\vtkShaderProgram.cxx, line 431
vtkShaderProgram (0000020B04DF6460): 


ERROR:root:#version 120
WARNING:root:ERROR: In C:\VPP\standalone-build\VTK-source\Rendering\OpenGL2\vtkShaderProgram.cxx, line 431
vtkShaderProgram (0000020B78175660): 


ERROR:root:Shader object was not initialized, cannot attach it.
ERROR:root:#version 120
WARNING:root:ERROR: In C:\VPP\standalone-build\VTK-source\Rendering\OpenGL2\vtkShaderProgram.cxx, line 431
vtkShaderProgram (0000020B78175660): 


ERROR:root:#version 120
WARNING:root:ERROR: In C:\VPP\standalone-build\VTK-source\Rendering\OpenGL2\vtkShaderProgram.cxx, line 431
vtkShaderProgram (0000020B78176000): 


ERROR:root:Shader object was not initialized, cannot attach it.
ERROR:root:#version 120
WARNING:root:ERROR: In C:\VPP\standalone-build\VTK-source\Rendering\OpenGL2\vtkShaderProgram.cxx, line 431
vtkShaderProgram (0000020B78176000): 


ERROR:root:#version 120
WARNING:root:ERROR: In C:\VPP\standalone-build\VTK-source\Rendering\OpenGL2\vtkShaderProgram.cxx, line 431
vtkShaderProgram (0000020B04DF6460): 


ERROR:root:#version 120
WARNING:root:ERROR: In C:\VPP\standalone-build\VTK-source\Rendering\OpenGL2\vtkShaderProgram.cxx, line 431
vtkShaderProgram (0000020B04DF6460): 


ERROR:root:#version 120
WARNING:root:ERROR: In C:\VPP\standalone-build\VTK-source\Rendering\OpenGL2\vtkShaderProgram.cxx, line 431
vtkShaderProgram (0000020B04DF6460): 


ERROR:root:Shader object was not initialized, cannot attach it.
ERROR:root:#version 120
WARNING:root:ERROR: In C:\VPP\standalone-build\VTK-source\Rendering\OpenGL2\vtkShaderProgram.cxx, line 431
vtkShaderProgram (0000020B04DF6460): 


ERROR:root:#version 120
WARNING:root:ERROR: In C:\VPP\standalone-build\VTK-source\Rendering\OpenGL2\vtkShaderProgram.cxx, line 431
vtkShaderProgram (0000020B04DF6460): 


ERROR:root:#version 120
WARNING:root:ERROR: In C:\VPP\standalone-build\VTK-source\Rendering\OpenGL2\vtkShaderProgram.cxx, line 431
vtkShaderProgram (0000020B04DF6460): 


ERROR:root:#version 120
WARNING:root:ERROR: In C:\VPP\standalone-build\VTK-source\Rendering\OpenGL2\vtkShaderProgram.cxx, line 431
vtkShaderProgram (0000020B04DF6460): 


ERROR:root:#version 120
WARNING:root:ERROR: In C:\VPP\standalone-build\VTK-source\Rendering\OpenGL2\vtkShaderProgram.cxx, line 431
vtkShaderProgram (0000020B04DF6460): 


ERROR:root:#version 120
WARNING:root:ERROR: In C:\VPP\standalone-build\VTK-source\Rendering\OpenGL2\vtkShaderProgram.cxx, line 431
vtkShaderProgram (0000020B04DF6460): 


ERROR:root:#version 120
WARNING:root:ERROR: In C:\VPP\standalone-build\VTK-source\Rendering\OpenGL2\vtkShaderProgram.cxx, line 431
vtkShaderProgram (0000020B78175660): 


ERROR:root:#version 120
WARNING:root:ERROR: In C:\VPP\standalone-build\VTK-source\Rendering\OpenGL2\vtkShaderProgram.cxx, line 431
vtkShaderProgram (0000020B78175660): 


ERROR:root:#version 120
WARNING:root:ERROR: In C:\VPP\standalone-build\VTK-source\Rendering\OpenGL2\vtkShaderProgram.cxx, line 431
vtkShaderProgram (0000020B78175660): 


ERROR:root:#version 120
WARNING:root:ERROR: In C:\VPP\standalone-build\VTK-source\Rendering\OpenGL2\vtkShaderProgram.cxx, line 431
vtkShaderProgram (0000020B78176000): 


ERROR:root:#version 120
WARNING:root:ERROR: In C:\VPP\standalone-build\VTK-source\Rendering\OpenGL2\vtkShaderProgram.cxx, line 431
vtkShaderProgram (0000020B78176000): 


ERROR:root:#version 120
WARNING:root:ERROR: In C:\VPP\standalone-build\VTK-source\Rendering\OpenGL2\vtkShaderProgram.cxx, line 431
vtkShaderProgram (0000020B78176000): 


ERROR:root:#version 120
WARNING:root:ERROR: In C:\VPP\standalone-build\VTK-source\Rendering\OpenGL2\vtkShaderProgram.cxx, line 431
vtkShaderProgram (0000020B04DF6460): 


ERROR:root:#version 120
WARNING:root:ERROR: In C:\VPP\standalone-build\VTK-source\Rendering\OpenGL2\vtkShaderProgram.cxx, line 431
vtkShaderProgram (0000020B04DF6460): 


ERROR:root:#version 120
```
Also, when I close the interactive window opened by vtki, apart from these errors showing up in the notebook the notebook becomes unresponsive (I have to restart the kernel) - but this behavior was probably already present when I originally reported the problem.

**Comment by banesullivan** [comment] 2019-04-22 13:34
Do you hit the exit button when closing? Could you try using the `q` key to close the window?

Looks like this is related to #135 

I’ll try to mimic this on a windows machine today

**Comment by mmagnuski** [comment] 2019-04-22 16:53
I can confirm that the error is due to closing via the close window button. Hitting `q` does not produce the error nor does it lead to kernel being unresponsive. Is it possible to create a CI vtki test emulating closing a window via clicking on the close button?

**Comment by banesullivan** [comment] 2019-04-22 17:13
> Is it possible to create a CI vtki test emulating closing a window via clicking on the close button?

I've been thinking about this lately and there should be a way to emulate key-press and mouse-press events, I just have no idea where to start in implementing this. 

Apologies for all the issues you've been running into - there's a lot of weirdness with Windows on the VTK backend that's difficult for us to catch being Mac and Linux users. Thanks for sticking with `vtki` through these bugs!

Could you please share all your system information? The windows machine I have access to isn't experiencing these bugs, so I wonder if its a GPU-specific, OpenGL version, or system architecture issue.

**Specifically, please share:**

- GPU details
- CPU details
- Windows version and architecture (is it x86?)
- VTK version: `import vtk; print(vtk.VTK_VERSION);` 
- Anything else the might be relevant in your system information that we may not be thinking of...

**Comment by mmagnuski** [comment] 2019-04-22 20:42
No problem, I know that it's often more difficult with Windows in open source, I'm happy to help debugging. :)

### System information:
* **CPU**: Intel i7-8750H, x64-based
* **OS**: Windows 10 Home (64-bit)
* **GPU**, this might potentially be a problem: I have two cards on my laptop: Intel UHD 630 and Nvidia Gforce GTX 1050 Ti; on my previous laptop I could easily define which programs are run with the Nvidia card, but with the current one such option does not seem to be readily accessible.
* **VTK**: 8.1.2
* can't think of other relevant things right now

**Comment by banesullivan** [comment] 2019-04-22 20:45
> this might potentially be a problem

ooo, yes. That could be a problem. My MacBook has a similar feature with an Intel graphics chip and an Nvidia card - VTK always triggers the Nvidia card to enable so I never experience any issues. If I had to guess, I'd say the inel chip is getting used which is why VTK is having issues with the shader:

> ```
> WARNING:root:ERROR: In C:\VPP\standalone-build\VTK-> source\Rendering\OpenGL2\vtkShaderProgram.cxx, line 431
> vtkShaderProgram (0000020B04DF6460): 
> ```

**Comment by mmagnuski** [comment] 2019-04-22 20:47
additional info (as given by `import mne; mne.sys_info()`):
```
Platform:      Windows-10-10.0.17763-SP0
Python:        3.6.6 |Anaconda, Inc.| (default, Jun 28 2018, 11:27:44) [MSC v.1900 64 bit (AMD64)]
Executable:    C:\Users\mmagn\Continuum\anaconda3\python.exe
CPU:           Intel64 Family 6 Model 158 Stepping 10, GenuineIntel: 12 cores
Memory:        15.9 GB

numpy:         1.16.2 {blas=mkl_rt, lapack=mkl_rt}
matplotlib:    3.0.2 {backend=module://ipykernel.pylab.backend_inline}
mayavi:        4.6.2 {qt_api=pyqt5, PyQt5=5.9.2}
```

**Comment by banesullivan** [comment] 2019-04-22 23:09
I have reproduced this issue on a windows machine I have access to that only has a GTX 1080 GPU

All is good on release `0.17.5` - the issue comes back in release `0.18.0`.

I'll look into the commit history to see what got changed

**Comment by banesullivan** [comment] 2019-04-22 23:25
Found the culprit in #150 - added a comment on the change that broke the exit button

**Comment by banesullivan** [comment] 2019-04-23 06:42
@mmagnuski, I presume you have a clone of the repo on your machine? If so, could you checkout the `close` branch and see if #190 fixes this issue - I won't have a chance to test on a Windows computer for a while.

**Comment by mmagnuski** [comment] 2019-04-23 08:51
Sure, I will check today.

**Comment by banesullivan** [comment] 2019-04-25 15:57
@mmagnuski: `v0.18.4` is out and this should be resolved!

**Comment by mmagnuski** [comment] 2019-04-25 17:44
Thanks! BTW, sorry for delay on my side: I saw  that you tested it on a windows machine before I got to it so I didn't think my input would be needed. But I have cloned the repo recently and installed in dev mode and can confirm closing the window works without problems now. :)

**Comment by banesullivan** [comment] 2019-10-23 19:19
@thast is seeing this happen again on Windows

**Comment by thast** [comment] 2019-10-23 19:25
Closing using the `x button` crash the kernel shortly after triggering an error: `ERROR:root:Shader object was not initialized, cannot attach it.`. Closing with `q` seems to work properly.

Behavior is consistent with `pyvista 0.21.2` and `pyvista 0.22.2`
My `vtk` is `8.1.2` (tried to upgrade to `8.2` but I got DLL issues with it)

**Comment by WeiGong123** [comment] 2019-11-07 09:18
Even closing with 'q' has a problem - after closing with 'q' for one window, other windows cannot be opened, just flash and then disappear.

**Comment by banesullivan** [comment] 2019-11-19 04:19
@WeiGong123, could you share a screen recording of this happening?

**Comment by WeiGong123** [comment] 2019-11-21 08:42
![pvReport](https://user-images.githubusercontent.com/49189032/69321330-ca4e7f80-0c3a-11ea-8bf5-06af8a4a1c32.png)

**Comment by WeiGong123** [comment] 2019-11-21 08:43
[pyvista.pptx](https://github.com/pyvista/pyvista/files/3873661/pyvista.pptx)

**Comment by WeiGong123** [comment] 2019-11-21 08:45
> @WeiGong123, could you share a screen recording of this happening?
> 
> And a system report:
> 
> ```python
> import pyvista as pv
> print(pv.Report())
> ```

Hi Bane, I am not sure whether you can view the screen recording in the ppt file.

**Comment by banesullivan** [comment] 2019-11-23 22:27
Thanks for sharing that screen recording, @WeiGong123! This is very strange behavior and appears to be a Windows issue - I'll see if I can reproduce this on my Windows VM but it looks like very strange behavior to track down.

**Closed** 2019-12-17 15:20 UTC
Labels: bug, duplicate
