### ISSUE TITLE
"Create a GIF Movie with updating textures" generates bad movie

### ISSUE THREAD

**Issue by spanag** [pyvista/pyvista#6696] opened 2024-10-09 10:43 UTC
### Describe the bug, what's wrong, and what you expected.

On https://docs.pyvista.org/examples/02-plot/texture.html#create-a-gif-movie-with-updating-textures :
The generated gif file shows only one frame, the rest are blank!

https://ezgif.com/split says there are only two frames, the second is blank and lasts longer.

I had the same issue on a Linux system, but on Windows the snippet works fine.  It's been present for some months, I don't know when the issue was introduced.

### Steps to reproduce the bug.

As seen on https://docs.pyvista.org/examples/02-plot/texture.html#create-a-gif-movie-with-updating-textures

```python
mesh = curvsurf.extract_surface()

# Create a plotter object
plotter = pv.Plotter(notebook=False, off_screen=True)

actor = plotter.add_mesh(mesh, smooth_shading=True, color="white")

# Open a gif
plotter.open_gif("texture.gif")

# Update Z and write a frame for each updated position
nframe = 15
for phase in np.linspace(0, 2 * np.pi, nframe + 1)[:nframe]:
    # create an image using numpy,
    z = np.sin(r + phase)
    mesh.points[:, -1] = z.ravel()

    # Creating a custom RGB image
    zz = A * np.exp(-0.5 * ((xx / b) ** 2.0 + (yy / b) ** 2.0))
    hue = norm(zz.ravel()) * 0.5 * (1.0 + np.sin(phase))
    colors = (cmap(hue)[:, 0:3] * 255.0).astype(np.uint8)
    image = colors.reshape((xx.shape[0], xx.shape[1], 3), order="F")

    # Convert 3D numpy array to texture
    actor.texture = pv.numpy_to_texture(image)

    # must update normals when smooth shading is enabled
    mesh.compute_normals(cell_normals=False, inplace=True)
    plotter.write_frame()
    plotter.clear()

# Closes and finalizes movie
plotter.close()
```

### System Information

```shell
https://docs.pyvista.org/
```

**Comment by banesullivan** [comment] 2024-10-10 05:32
Huh! Thank you for bringing this to our attention! That is definitely unexpected

**Comment by user27182** [comment] 2024-10-21 15:04
Thanks for reporting, this is a duplicate of https://github.com/pyvista/pyvista/issues/6297.

The old documentation is no longer available for viewing but I believe this is broken as of `0.43`

**Closed** 2024-10-21 15:07 UTC
Labels: bug

**Comment by banesullivan** [comment] 2024-10-25 01:09
> The old documentation is no longer available for viewing

Technically I'm still hosting some of the old documentation versions on netlify and I'm making a manual effort to archive releases on my netlfify account

Confirmed broken in 0.43: https://pyvista-0-43.netlify.app/examples/02-plot/texture#sphx-glr-examples-02-plot-texture-py

Confirmed working in 0.42: https://pyvista-0-42.netlify.app/examples/02-plot/texture#sphx-glr-examples-02-plot-texture-py
