### ISSUE TITLE
pythreejs Plotter support for point labels

### ISSUE THREAD

**Issue by darikg** [pyvista/pyvista#2962] opened 2022-07-09 19:45 UTC
### Describe the feature you would like to be added.

The pythreejs plotter currently does not support point labels. It'd be nice to have this since the pythreejs/jupyterlab integration is really nice.

I've poked around a bit and found:

1) Pyvista's pythreejs adapter works by converting the actors in the VTK plotter to their pythreejs equivalents
2) `Plotter.add_point_labels(..., show_points=True)` adds two actors: 
  - an actor whose `GetMapper().GetInputAsDataSet()` returns a PolyData with the corresponding points, and label values stored in `point_data['labels']`
  - an actor whose `GetMapper()` returns a `vtkLabelPlacementMapper` that does not have a `GetInputAsDataSet` method
3) with `Plotter.add_point_labels(..., show_points=False)`, only the latter of the two actors above is added

It seems like it'd be pretty easy to pull points and labels out of that first actor, and represent them as pythreejs `TextGeometry` objects, but if `show_points=False` is used, I don't know how to get the points/labels out of that `vtkLabelPlacementMapper`.

cc @akaszynski, I think you did all the original pythreejs work?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by akaszynski** [comment] 2022-07-10 14:22
> It'd be nice to have this since the pythreejs/jupyterlab integration is really nice.

Fully agree. It's a missing feature I've been meaning to add.

> cc @akaszynski, I think you did all the original pythreejs work?

Yes, and it's a bit of work, not sure how much I'll be able to maintain it without help.

**Comment by darikg** [comment] 2022-07-10 20:19
> Yes, and it's a bit of work
I'm sure! I'm happy to submit a PR here, just not sure how to use the vtkLabelPlacementMapper. Or do you think it'd be ok to just require the original `add_point_labels` have `use show_points=True`?

**Comment by akaszynski** [comment] 2022-07-10 23:36
> > Yes, and it's a bit of work
> 
> I'm sure! I'm happy to submit a PR here, just not sure how to use the vtkLabelPlacementMapper. Or do you think it'd be ok to just require the original `add_point_labels` have `use show_points=True`?

I think that's acceptable. Just as long as you raise a helpful `ValueError` to let the user know what the issue is.

**Comment by darikg** [comment] 2022-07-12 12:19
Ah, looks like pythreejs hasn't implemented TextGeometry yet https://github.com/jupyter-widgets/pythreejs/issues/199

**Comment by banesullivan** [comment] 2023-01-27 18:34
Closing as we don't plan on further developing the `pythreejs` jupyter backend. This may be possible with the new trame-based backend in the future, but is also currently limited by VTK.js not support text actors

**Closed by banesullivan** 2023-01-27 18:34 UTC
Labels: feature-request
