### ISSUE TITLE
BUG: View rotates for wrong subplot on click-and-drag

### ISSUE THREAD

**Issue by larsoner** [pyvista/pyvista#851] opened 2020-07-29 20:13 UTC
Click-and-drag in a subplot should "capture" the click event so that dragging anywhere continues to change the view in that subplot. Currently it does not (only one click-drag occurs in the below GIF):

<details>
<summary>Code example</summary>

```
import pyvista as pv
from pyvista import examples
mesh = examples.download_cow()
decimated = mesh.decimate_boundary(target_reduction=0.75)
p = pv.Plotter(notebook=0, shape=(1, 2), border=False)
p.subplot(0, 0)
p.add_text("Original mesh", font_size=24)
p.add_mesh(mesh, show_edges=True, color=True)
p.subplot(0, 1)
p.add_text("Decimated version", font_size=24)
p.add_mesh(decimated, color=True, show_edges=True)
p.open_gif("linked.gif")
p.show()
```

</details>

![click-drag](https://user-images.githubusercontent.com/2365790/88848381-63646b80-d1b6-11ea-94b7-58d1f819f1d4.gif)

Moving the mouse outside the window entirely allows to continue rotating the correct view, which is good. But really it should work wherever you move your mouse on the screen after clicking (it should not matter if you enter another subplot's space).

**Comment by banesullivan** [comment] 2020-07-30 03:33
Duplicate of #116 - there are workarounds but nothing super clean

**Comment by larsoner** [comment] 2020-07-30 03:38
Yep, sorry should have checked better!

**Closed** 2020-07-30 03:38 UTC
Labels: duplicate

**Comment by banesullivan** [comment] 2020-07-30 03:39
All good! That's a very old issue. I'm glad this is on your radar too as it has bugged me for 1.5 years now
