### ISSUE TITLE
Creating movies not working

### ISSUE THREAD

**Issue by RafaelLuz** [pyvista/pyvista#3584] opened 2022-11-11 03:54 UTC
### Describe the bug, what's wrong, and what you expected.

After I started using python 3.10 with pyvista 0.37 my scripts to create mp4 movies stopped working. Not even the example in the documentation is running ([Create a MP4 Movie](https://docs.pyvista.org/examples/02-plot/movie.html) ) due to the same error. This is the stacktrace I got from both my script and the example:

```
Traceback (most recent call last):
  File "/home/rafael/...", line 39, in <module>
    plotter.write_frame()  # Write this frame
  File "/home/rafael/.pyenv/versions/.../lib/python3.10/site-packages/pyvista/plotting/plotting.py", line 4365, in write_frame
    self.update()
  File "/home/rafael/.pyenv/versions/.../lib/python3.10/site-packages/pyvista/plotting/plotting.py", line 1943, in update
    self.right_timer_id = self.iren.create_repeating_timer(stime)
  File "/home/rafael/.pyenv/versions/.../lib/python3.10/site-packages/pyvista/plotting/render_window_interactor.py", line 780, in create_repeating_timer
    self.interactor.DestroyTimer(timer_id)
AttributeError: 'NoneType' object has no attribute 'DestroyTimer'
```

Does anyone know how to solve or have any workaround for it? Go back to a previous version of python is not an option for me. Thank you all in advance!

### Steps to reproduce the bug.

just try to execute the example

### System Information

```shell
--------------------------------------------------------------------------------
  Date: Fri Nov 11 00:49:07 2022 -03

                OS : Linux
            CPU(s) : 16
           Machine : x86_64
      Architecture : 64bit
       Environment : Python
        GPU Vendor : NVIDIA Corporation
      GPU Renderer : NVIDIA GeForce GTX 1660 Ti/PCIe/SSE2
       GPU Version : 4.5.0 NVIDIA 520.56.06

  Python 3.10.8 (main, Nov  7 2022, 20:05:38) [GCC 12.2.0]

           pyvista : 0.37.0
               vtk : 9.2.2
             numpy : 1.23.4
           imageio : 2.22.4
            scooby : 0.7.0
             pooch : v1.6.0
        matplotlib : 3.6.2
         pyvistaqt : 0.9.0
             PyQt5 : 5.15.7
             scipy : 1.9.3
--------------------------------------------------------------------------------
```

**Comment by banesullivan** [comment] 2022-11-11 04:07
I believe this is a duplicate of #3560

**Closed** 2022-12-14 15:07 UTC
Labels: bug
